class Country {
  final String code;          // Code ISO2 (ex: "fr")
  final String name;          // Nom complet
  final String dialCode;      // Indicatif (ex: "+33")
  final String iso3;          // Code ISO3 (ex: "FRA")
  final String currency;      // Code devise (ex: "EUR")
  final String currencyName;  // Nom devise (ex: "Euro")
  final String emoji;         // Emoji drapeau (ex: "🇫🇷")
  final List<String> timezones; // Fuseaux horaires (ex: ["UTC+01:00"])
  final String region;        // Continent (ex: "Europe")

  const Country({
    required this.code,
    required this.name,
    required this.dialCode,
    required this.iso3,
    required this.currency,
    required this.currencyName,
    required this.emoji,
    required this.timezones,
    required this.region,
  });

  @override
  bool operator ==(Object other) =>
      identical(this, other) || other is Country && code == other.code;

  @override
  int get hashCode => code.hashCode;
}





const List<Country> defaultCountries = [
  Country(
    code: 'ad',
    name: 'Andorre',
    dialCode: '+376',
    iso3: 'AND',
    currency: 'EUR',
    currencyName: 'Euro',
    emoji: '🇦🇩',
    timezones: ['UTC+01:00'],
    region: 'Europe',
  ),
  Country(
    code: 'ae',
    name: 'Émirats Arabes Unis',
    dialCode: '+971',
    iso3: 'ARE',
    currency: 'AED',
    currencyName: 'Dirham des Émirats',
    emoji: '🇦🇪',
    timezones: ['UTC+04:00'],
    region: 'Asia',
  ),
  Country(
    code: 'af',
    name: 'Afghanistan',
    dialCode: '+93',
    iso3: 'AFG',
    currency: 'AFN',
    currencyName: 'Afghani',
    emoji: '🇦🇫',
    timezones: ['UTC+04:30'],
    region: 'Asia',
  ),
  Country(
    code: 'ag',
    name: 'Antigua-et-Barbuda',
    dialCode: '+1268',
    iso3: 'ATG',
    currency: 'XCD',
    currencyName: 'Dollar des Caraïbes orientales',
    emoji: '🇦🇬',
    timezones: ['UTC-04:00'],
    region: 'Americas',
  ),
  Country(
    code: 'ai',
    name: 'Anguilla',
    dialCode: '+1264',
    iso3: 'AIA',
    currency: 'XCD',
    currencyName: 'Dollar des Caraïbes orientales',
    emoji: '🇦🇮',
    timezones: ['UTC-04:00'],
    region: 'Americas',
  ),
  Country(
    code: 'al',
    name: 'Albanie',
    dialCode: '+355',
    iso3: 'ALB',
    currency: 'ALL',
    currencyName: 'Lek albanais',
    emoji: '🇦🇱',
    timezones: ['UTC+01:00'],
    region: 'Europe',
  ),
  Country(
    code: 'am',
    name: 'Arménie',
    dialCode: '+374',
    iso3: 'ARM',
    currency: 'AMD',
    currencyName: 'Dram arménien',
    emoji: '🇦🇲',
    timezones: ['UTC+04:00'],
    region: 'Asia',
  ),
  Country(
    code: 'ao',
    name: 'Angola',
    dialCode: '+244',
    iso3: 'AGO',
    currency: 'AOA',
    currencyName: 'Kwanza angolais',
    emoji: '🇦🇴',
    timezones: ['UTC+01:00'],
    region: 'Africa',
  ),
  Country(
    code: 'ar',
    name: 'Argentine',
    dialCode: '+54',
    iso3: 'ARG',
    currency: 'ARS',
    currencyName: 'Peso argentin',
    emoji: '🇦🇷',
    timezones: ['UTC-03:00'],
    region: 'Americas',
  ),
  Country(
    code: 'at',
    name: 'Autriche',
    dialCode: '+43',
    iso3: 'AUT',
    currency: 'EUR',
    currencyName: 'Euro',
    emoji: '🇦🇹',
    timezones: ['UTC+01:00'],
    region: 'Europe',
  ),
  Country(
    code: 'au',
    name: 'Australie',
    dialCode: '+61',
    iso3: 'AUS',
    currency: 'AUD',
    currencyName: 'Dollar australien',
    emoji: '🇦🇺',
    timezones: ['UTC+08:00', 'UTC+09:30', 'UTC+10:00'],
    region: 'Oceania',
  ),
  Country(
    code: 'az',
    name: 'Azerbaïdjan',
    dialCode: '+994',
    iso3: 'AZE',
    currency: 'AZN',
    currencyName: 'Manat azerbaïdjanais',
    emoji: '🇦🇿',
    timezones: ['UTC+04:00'],
    region: 'Asia',
  ),
  Country(
    code: 'ba',
    name: 'Bosnie-Herzégovine',
    dialCode: '+387',
    iso3: 'BIH',
    currency: 'BAM',
    currencyName: 'Mark convertible',
    emoji: '🇧🇦',
    timezones: ['UTC+01:00'],
    region: 'Europe',
  ),
  Country(
    code: 'bb',
    name: 'Barbade',
    dialCode: '+1246',
    iso3: 'BRB',
    currency: 'BBD',
    currencyName: 'Dollar barbadien',
    emoji: '🇧🇧',
    timezones: ['UTC-04:00'],
    region: 'Americas',
  ),
  Country(
    code: 'bd',
    name: 'Bangladesh',
    dialCode: '+880',
    iso3: 'BGD',
    currency: 'BDT',
    currencyName: 'Taka bangladais',
    emoji: '🇧🇩',
    timezones: ['UTC+06:00'],
    region: 'Asia',
  ),
  Country(
    code: 'be',
    name: 'Belgique',
    dialCode: '+32',
    iso3: 'BEL',
    currency: 'EUR',
    currencyName: 'Euro',
    emoji: '🇧🇪',
    timezones: ['UTC+01:00'],
    region: 'Europe',
  ),
  Country(
    code: 'bf',
    name: 'Burkina Faso',
    dialCode: '+226',
    iso3: 'BFA',
    currency: 'XOF',
    currencyName: 'Franc CFA (BCEAO)',
    emoji: '🇧🇫',
    timezones: ['UTC'],
    region: 'Africa',
  ),
  Country(
    code: 'bg',
    name: 'Bulgarie',
    dialCode: '+359',
    iso3: 'BGR',
    currency: 'BGN',
    currencyName: 'Lev bulgare',
    emoji: '🇧🇬',
    timezones: ['UTC+02:00'],
    region: 'Europe',
  ),
  Country(
    code: 'bh',
    name: 'Bahreïn',
    dialCode: '+973',
    iso3: 'BHR',
    currency: 'BHD',
    currencyName: 'Dinar bahreïni',
    emoji: '🇧🇭',
    timezones: ['UTC+03:00'],
    region: 'Asia',
  ),
  Country(
    code: 'bi',
    name: 'Burundi',
    dialCode: '+257',
    iso3: 'BDI',
    currency: 'BIF',
    currencyName: 'Franc burundais',
    emoji: '🇧🇮',
    timezones: ['UTC+02:00'],
    region: 'Africa',
  ),
  Country(
    code: 'bj',
    name: 'Bénin',
    dialCode: '+229',
    iso3: 'BEN',
    currency: 'XOF',
    currencyName: 'Franc CFA (BCEAO)',
    emoji: '🇧🇯',
    timezones: ['UTC+01:00'],
    region: 'Africa',
  ),
  Country(
    code: 'bn',
    name: 'Brunei',
    dialCode: '+673',
    iso3: 'BRN',
    currency: 'BND',
    currencyName: 'Dollar de Brunei',
    emoji: '🇧🇳',
    timezones: ['UTC+08:00'],
    region: 'Asia',
  ),
  Country(
    code: 'bo',
    name: 'Bolivie',
    dialCode: '+591',
    iso3: 'BOL',
    currency: 'BOB',
    currencyName: 'Boliviano',
    emoji: '🇧🇴',
    timezones: ['UTC-04:00'],
    region: 'Americas',
  ),
  Country(
    code: 'br',
    name: 'Brésil',
    dialCode: '+55',
    iso3: 'BRA',
    currency: 'BRL',
    currencyName: 'Real brésilien',
    emoji: '🇧🇷',
    timezones: ['UTC-05:00', 'UTC-04:00', 'UTC-03:00', 'UTC-02:00'],
    region: 'Americas',
  ),
  Country(
    code: 'bs',
    name: 'Bahamas',
    dialCode: '+1242',
    iso3: 'BHS',
    currency: 'BSD',
    currencyName: 'Dollar bahaméen',
    emoji: '🇧🇸',
    timezones: ['UTC-05:00'],
    region: 'Americas',
  ),
  Country(
    code: 'bt',
    name: 'Bhoutan',
    dialCode: '+975',
    iso3: 'BTN',
    currency: 'BTN',
    currencyName: 'Ngultrum',
    emoji: '🇧🇹',
    timezones: ['UTC+06:00'],
    region: 'Asia',
  ),
  Country(
    code: 'bw',
    name: 'Botswana',
    dialCode: '+267',
    iso3: 'BWA',
    currency: 'BWP',
    currencyName: 'Pula botswanais',
    emoji: '🇧🇼',
    timezones: ['UTC+02:00'],
    region: 'Africa',
  ),
  Country(
    code: 'by',
    name: 'Biélorussie',
    dialCode: '+375',
    iso3: 'BLR',
    currency: 'BYN',
    currencyName: 'Rouble biélorusse',
    emoji: '🇧🇾',
    timezones: ['UTC+03:00'],
    region: 'Europe',
  ),
  Country(
    code: 'bz',
    name: 'Belize',
    dialCode: '+501',
    iso3: 'BLZ',
    currency: 'BZD',
    currencyName: 'Dollar bélizien',
    emoji: '🇧🇿',
    timezones: ['UTC-06:00'],
    region: 'Americas',
  ),
  Country(
    code: 'ca',
    name: 'Canada',
    dialCode: '+1',
    iso3: 'CAN',
    currency: 'CAD',
    currencyName: 'Dollar canadien',
    emoji: '🇨🇦',
    timezones: ['UTC-08:00', 'UTC-07:00', 'UTC-06:00', 'UTC-05:00'],
    region: 'Americas',
  ),
  Country(
    code: 'cd',
    name: 'République Démocratique du Congo',
    dialCode: '+243',
    iso3: 'COD',
    currency: 'CDF',
    currencyName: 'Franc congolais',
    emoji: '🇨🇩',
    timezones: ['UTC+01:00', 'UTC+02:00'],
    region: 'Africa',
  ),
  Country(
    code: 'cf',
    name: 'République Centrafricaine',
    dialCode: '+236',
    iso3: 'CAF',
    currency: 'XAF',
    currencyName: 'Franc CFA (BEAC)',
    emoji: '🇨🇫',
    timezones: ['UTC+01:00'],
    region: 'Africa',
  ),
  Country(
    code: 'cg',
    name: 'République du Congo',
    dialCode: '+242',
    iso3: 'COG',
    currency: 'XAF',
    currencyName: 'Franc CFA (BEAC)',
    emoji: '🇨🇬',
    timezones: ['UTC+01:00'],
    region: 'Africa',
  ),
  Country(
    code: 'ch',
    name: 'Suisse',
    dialCode: '+41',
    iso3: 'CHE',
    currency: 'CHF',
    currencyName: 'Franc suisse',
    emoji: '🇨🇭',
    timezones: ['UTC+01:00'],
    region: 'Europe',
  ),
  Country(
    code: 'ci',
    name: 'Côte d\'Ivoire',
    dialCode: '+225',
    iso3: 'CIV',
    currency: 'XOF',
    currencyName: 'Franc CFA (BCEAO)',
    emoji: '🇨🇮',
    timezones: ['UTC'],
    region: 'Africa',
  ),
  Country(
    code: 'cl',
    name: 'Chili',
    dialCode: '+56',
    iso3: 'CHL',
    currency: 'CLP',
    currencyName: 'Peso chilien',
    emoji: '🇨🇱',
    timezones: ['UTC-06:00', 'UTC-04:00'],
    region: 'Americas',
  ),
  Country(
    code: 'cm',
    name: 'Cameroun',
    dialCode: '+237',
    iso3: 'CMR',
    currency: 'XAF',
    currencyName: 'Franc CFA (BEAC)',
    emoji: '🇨🇲',
    timezones: ['UTC+01:00'],
    region: 'Africa',
  ),
  Country(
    code: 'cn',
    name: 'Chine',
    dialCode: '+86',
    iso3: 'CHN',
    currency: 'CNY',
    currencyName: 'Yuan renminbi',
    emoji: '🇨🇳',
    timezones: ['UTC+08:00'],
    region: 'Asia',
  ),
  Country(
    code: 'co',
    name: 'Colombie',
    dialCode: '+57',
    iso3: 'COL',
    currency: 'COP',
    currencyName: 'Peso colombien',
    emoji: '🇨🇴',
    timezones: ['UTC-05:00'],
    region: 'Americas',
  ),
  Country(
    code: 'cr',
    name: 'Costa Rica',
    dialCode: '+506',
    iso3: 'CRI',
    currency: 'CRC',
    currencyName: 'Colón costaricien',
    emoji: '🇨🇷',
    timezones: ['UTC-06:00'],
    region: 'Americas',
  ),
  Country(
    code: 'cu',
    name: 'Cuba',
    dialCode: '+53',
    iso3: 'CUB',
    currency: 'CUP',
    currencyName: 'Peso cubain',
    emoji: '🇨🇺',
    timezones: ['UTC-05:00'],
    region: 'Americas',
  ),
  Country(
    code: 'cv',
    name: 'Cap-Vert',
    dialCode: '+238',
    iso3: 'CPV',
    currency: 'CVE',
    currencyName: 'Escudo cap-verdien',
    emoji: '🇨🇻',
    timezones: ['UTC-01:00'],
    region: 'Africa',
  ),
  Country(
    code: 'cy',
    name: 'Chypre',
    dialCode: '+357',
    iso3: 'CYP',
    currency: 'EUR',
    currencyName: 'Euro',
    emoji: '🇨🇾',
    timezones: ['UTC+02:00'],
    region: 'Europe',
  ),
  Country(
    code: 'cz',
    name: 'République Tchèque',
    dialCode: '+420',
    iso3: 'CZE',
    currency: 'CZK',
    currencyName: 'Couronne tchèque',
    emoji: '🇨🇿',
    timezones: ['UTC+01:00'],
    region: 'Europe',
  ),
  Country(
    code: 'de',
    name: 'Allemagne',
    dialCode: '+49',
    iso3: 'DEU',
    currency: 'EUR',
    currencyName: 'Euro',
    emoji: '🇩🇪',
    timezones: ['UTC+01:00'],
    region: 'Europe',
  ),
  Country(
    code: 'dj',
    name: 'Djibouti',
    dialCode: '+253',
    iso3: 'DJI',
    currency: 'DJF',
    currencyName: 'Franc djiboutien',
    emoji: '🇩🇯',
    timezones: ['UTC+03:00'],
    region: 'Africa',
  ),
  Country(
    code: 'dk',
    name: 'Danemark',
    dialCode: '+45',
    iso3: 'DNK',
    currency: 'DKK',
    currencyName: 'Couronne danoise',
    emoji: '🇩🇰',
    timezones: ['UTC+01:00'],
    region: 'Europe',
  ),
  Country(
    code: 'dm',
    name: 'Dominique',
    dialCode: '+1767',
    iso3: 'DMA',
    currency: 'XCD',
    currencyName: 'Dollar des Caraïbes orientales',
    emoji: '🇩🇲',
    timezones: ['UTC-04:00'],
    region: 'Americas',
  ),
  Country(
    code: 'do',
    name: 'République Dominicaine',
    dialCode: '+1809',
    iso3: 'DOM',
    currency: 'DOP',
    currencyName: 'Peso dominicain',
    emoji: '🇩🇴',
    timezones: ['UTC-04:00'],
    region: 'Americas',
  ),
  Country(
    code: 'dz',
    name: 'Algérie',
    dialCode: '+213',
    iso3: 'DZA',
    currency: 'DZD',
    currencyName: 'Dinar algérien',
    emoji: '🇩🇿',
    timezones: ['UTC+01:00'],
    region: 'Africa',
  ),
  Country(
    code: 'ec',
    name: 'Équateur',
    dialCode: '+593',
    iso3: 'ECU',
    currency: 'USD',
    currencyName: 'Dollar américain',
    emoji: '🇪🇨',
    timezones: ['UTC-06:00', 'UTC-05:00'],
    region: 'Americas',
  ),
  Country(
    code: 'ee',
    name: 'Estonie',
    dialCode: '+372',
    iso3: 'EST',
    currency: 'EUR',
    currencyName: 'Euro',
    emoji: '🇪🇪',
    timezones: ['UTC+02:00'],
    region: 'Europe',
  ),
  Country(
    code: 'eg',
    name: 'Égypte',
    dialCode: '+20',
    iso3: 'EGY',
    currency: 'EGP',
    currencyName: 'Livre égyptienne',
    emoji: '🇪🇬',
    timezones: ['UTC+02:00'],
    region: 'Africa',
  ),
  Country(
    code: 'er',
    name: 'Érythrée',
    dialCode: '+291',
    iso3: 'ERI',
    currency: 'ERN',
    currencyName: 'Nakfa érythréen',
    emoji: '🇪🇷',
    timezones: ['UTC+03:00'],
    region: 'Africa',
  ),
  Country(
    code: 'es',
    name: 'Espagne',
    dialCode: '+34',
    iso3: 'ESP',
    currency: 'EUR',
    currencyName: 'Euro',
    emoji: '🇪🇸',
    timezones: ['UTC', 'UTC+01:00'],
    region: 'Europe',
  ),
  Country(
    code: 'et',
    name: 'Éthiopie',
    dialCode: '+251',
    iso3: 'ETH',
    currency: 'ETB',
    currencyName: 'Birr éthiopien',
    emoji: '🇪🇹',
    timezones: ['UTC+03:00'],
    region: 'Africa',
  ),
  Country(
    code: 'fi',
    name: 'Finlande',
    dialCode: '+358',
    iso3: 'FIN',
    currency: 'EUR',
    currencyName: 'Euro',
    emoji: '🇫🇮',
    timezones: ['UTC+02:00'],
    region: 'Europe',
  ),
  Country(
    code: 'fj',
    name: 'Fidji',
    dialCode: '+679',
    iso3: 'FJI',
    currency: 'FJD',
    currencyName: 'Dollar fidjien',
    emoji: '🇫🇯',
    timezones: ['UTC+12:00'],
    region: 'Oceania',
  ),
  Country(
    code: 'fr',
    name: 'France',
    dialCode: '+33',
    iso3: 'FRA',
    currency: 'EUR',
    currencyName: 'Euro',
    emoji: '🇫🇷',
    timezones: ['UTC+01:00'],
    region: 'Europe',
  ),
  Country(
    code: 'ga',
    name: 'Gabon',
    dialCode: '+241',
    iso3: 'GAB',
    currency: 'XAF',
    currencyName: 'Franc CFA (BEAC)',
    emoji: '🇬🇦',
    timezones: ['UTC+01:00'],
    region: 'Africa',
  ),
  Country(
    code: 'gb',
    name: 'Royaume-Uni',
    dialCode: '+44',
    iso3: 'GBR',
    currency: 'GBP',
    currencyName: 'Livre sterling',
    emoji: '🇬🇧',
    timezones: ['UTC', 'UTC+01:00'],
    region: 'Europe',
  ),
  Country(
    code: 'gd',
    name: 'Grenade',
    dialCode: '+1473',
    iso3: 'GRD',
    currency: 'XCD',
    currencyName: 'Dollar des Caraïbes orientales',
    emoji: '🇬🇩',
    timezones: ['UTC-04:00'],
    region: 'Americas',
  ),
  Country(
    code: 'ge',
    name: 'Géorgie',
    dialCode: '+995',
    iso3: 'GEO',
    currency: 'GEL',
    currencyName: 'Lari géorgien',
    emoji: '🇬🇪',
    timezones: ['UTC+04:00'],
    region: 'Asia',
  ),
  Country(
    code: 'gh',
    name: 'Ghana',
    dialCode: '+233',
    iso3: 'GHA',
    currency: 'GHS',
    currencyName: 'Cedi ghanéen',
    emoji: '🇬🇭',
    timezones: ['UTC'],
    region: 'Africa',
  ),
  Country(
    code: 'gm',
    name: 'Gambie',
    dialCode: '+220',
    iso3: 'GMB',
    currency: 'GMD',
    currencyName: 'Dalasi gambien',
    emoji: '🇬🇲',
    timezones: ['UTC'],
    region: 'Africa',
  ),
  Country(
    code: 'gn',
    name: 'Guinée',
    dialCode: '+224',
    iso3: 'GIN',
    currency: 'GNF',
    currencyName: 'Franc guinéen',
    emoji: '🇬🇳',
    timezones: ['UTC'],
    region: 'Africa',
  ),
  Country(
    code: 'gq',
    name: 'Guinée équatoriale',
    dialCode: '+240',
    iso3: 'GNQ',
    currency: 'XAF',
    currencyName: 'Franc CFA (BEAC)',
    emoji: '🇬🇶',
    timezones: ['UTC+01:00'],
    region: 'Africa',
  ),
  Country(
    code: 'gr',
    name: 'Grèce',
    dialCode: '+30',
    iso3: 'GRC',
    currency: 'EUR',
    currencyName: 'Euro',
    emoji: '🇬🇷',
    timezones: ['UTC+02:00'],
    region: 'Europe',
  ),
  Country(
    code: 'gt',
    name: 'Guatemala',
    dialCode: '+502',
    iso3: 'GTM',
    currency: 'GTQ',
    currencyName: 'Quetzal guatémaltèque',
    emoji: '🇬🇹',
    timezones: ['UTC-06:00'],
    region: 'Americas',
  ),
  Country(
    code: 'gw',
    name: 'Guinée-Bissau',
    dialCode: '+245',
    iso3: 'GNB',
    currency: 'XOF',
    currencyName: 'Franc CFA (BCEAO)',
    emoji: '🇬🇼',
    timezones: ['UTC'],
    region: 'Africa',
  ),
  Country(
    code: 'gy',
    name: 'Guyana',
    dialCode: '+592',
    iso3: 'GUY',
    currency: 'GYD',
    currencyName: 'Dollar guyanais',
    emoji: '🇬🇾',
    timezones: ['UTC-04:00'],
    region: 'Americas',
  ),
  Country(
    code: 'hk',
    name: 'Hong Kong',
    dialCode: '+852',
    iso3: 'HKG',
    currency: 'HKD',
    currencyName: 'Dollar de Hong Kong',
    emoji: '🇭🇰',
    timezones: ['UTC+08:00'],
    region: 'Asia',
  ),
  Country(
    code: 'hn',
    name: 'Honduras',
    dialCode: '+504',
    iso3: 'HND',
    currency: 'HNL',
    currencyName: 'Lempira hondurien',
    emoji: '🇭🇳',
    timezones: ['UTC-06:00'],
    region: 'Americas',
  ),
  Country(
    code: 'hr',
    name: 'Croatie',
    dialCode: '+385',
    iso3: 'HRV',
    currency: 'HRK',
    currencyName: 'Kuna croate',
    emoji: '🇭🇷',
    timezones: ['UTC+01:00'],
    region: 'Europe',
  ),
  Country(
    code: 'ht',
    name: 'Haïti',
    dialCode: '+509',
    iso3: 'HTI',
    currency: 'HTG',
    currencyName: 'Gourde haïtienne',
    emoji: '🇭🇹',
    timezones: ['UTC-05:00'],
    region: 'Americas',
  ),
  Country(
    code: 'hu',
    name: 'Hongrie',
    dialCode: '+36',
    iso3: 'HUN',
    currency: 'HUF',
    currencyName: 'Forint hongrois',
    emoji: '🇭🇺',
    timezones: ['UTC+01:00'],
    region: 'Europe',
  ),
  Country(
    code: 'id',
    name: 'Indonésie',
    dialCode: '+62',
    iso3: 'IDN',
    currency: 'IDR',
    currencyName: 'Roupie indonésienne',
    emoji: '🇮🇩',
    timezones: ['UTC+07:00', 'UTC+08:00', 'UTC+09:00'],
    region: 'Asia',
  ),
  Country(
    code: 'ie',
    name: 'Irlande',
    dialCode: '+353',
    iso3: 'IRL',
    currency: 'EUR',
    currencyName: 'Euro',
    emoji: '🇮🇪',
    timezones: ['UTC', 'UTC+01:00'],
    region: 'Europe',
  ),
  Country(
    code: 'il',
    name: 'Israël',
    dialCode: '+972',
    iso3: 'ISR',
    currency: 'ILS',
    currencyName: 'Nouveau shekel israélien',
    emoji: '🇮🇱',
    timezones: ['UTC+02:00'],
    region: 'Asia',
  ),
  Country(
    code: 'in',
    name: 'Inde',
    dialCode: '+91',
    iso3: 'IND',
    currency: 'INR',
    currencyName: 'Roupie indienne',
    emoji: '🇮🇳',
    timezones: ['UTC+05:30'],
    region: 'Asia',
  ),
  Country(
    code: 'iq',
    name: 'Irak',
    dialCode: '+964',
    iso3: 'IRQ',
    currency: 'IQD',
    currencyName: 'Dinar irakien',
    emoji: '🇮🇶',
    timezones: ['UTC+03:00'],
    region: 'Asia',
  ),
  Country(
    code: 'ir',
    name: 'Iran',
    dialCode: '+98',
    iso3: 'IRN',
    currency: 'IRR',
    currencyName: 'Rial iranien',
    emoji: '🇮🇷',
    timezones: ['UTC+03:30'],
    region: 'Asia',
  ),
  Country(
    code: 'is',
    name: 'Islande',
    dialCode: '+354',
    iso3: 'ISL',
    currency: 'ISK',
    currencyName: 'Couronne islandaise',
    emoji: '🇮🇸',
    timezones: ['UTC'],
    region: 'Europe',
  ),
  Country(
    code: 'it',
    name: 'Italie',
    dialCode: '+39',
    iso3: 'ITA',
    currency: 'EUR',
    currencyName: 'Euro',
    emoji: '🇮🇹',
    timezones: ['UTC+01:00'],
    region: 'Europe',
  ),
  Country(
    code: 'jm',
    name: 'Jamaïque',
    dialCode: '+1876',
    iso3: 'JAM',
    currency: 'JMD',
    currencyName: 'Dollar jamaïcain',
    emoji: '🇯🇲',
    timezones: ['UTC-05:00'],
    region: 'Americas',
  ),
  Country(
    code: 'jo',
    name: 'Jordanie',
    dialCode: '+962',
    iso3: 'JOR',
    currency: 'JOD',
    currencyName: 'Dinar jordanien',
    emoji: '🇯🇴',
    timezones: ['UTC+02:00'],
    region: 'Asia',
  ),
  Country(
    code: 'jp',
    name: 'Japon',
    dialCode: '+81',
    iso3: 'JPN',
    currency: 'JPY',
    currencyName: 'Yen japonais',
    emoji: '🇯🇵',
    timezones: ['UTC+09:00'],
    region: 'Asia',
  ),
  Country(
    code: 'ke',
    name: 'Kenya',
    dialCode: '+254',
    iso3: 'KEN',
    currency: 'KES',
    currencyName: 'Shilling kényan',
    emoji: '🇰🇪',
    timezones: ['UTC+03:00'],
    region: 'Africa',
  ),
  Country(
    code: 'kg',
    name: 'Kirghizistan',
    dialCode: '+996',
    iso3: 'KGZ',
    currency: 'KGS',
    currencyName: 'Som kirghize',
    emoji: '🇰🇬',
    timezones: ['UTC+06:00'],
    region: 'Asia',
  ),
  Country(
    code: 'kh',
    name: 'Cambodge',
    dialCode: '+855',
    iso3: 'KHM',
    currency: 'KHR',
    currencyName: 'Riel cambodgien',
    emoji: '🇰🇭',
    timezones: ['UTC+07:00'],
    region: 'Asia',
  ),
  Country(
    code: 'ki',
    name: 'Kiribati',
    dialCode: '+686',
    iso3: 'KIR',
    currency: 'AUD',
    currencyName: 'Dollar australien',
    emoji: '🇰🇮',
    timezones: ['UTC+12:00', 'UTC+13:00', 'UTC+14:00'],
    region: 'Oceania',
  ),
  Country(
    code: 'km',
    name: 'Comores',
    dialCode: '+269',
    iso3: 'COM',
    currency: 'KMF',
    currencyName: 'Franc comorien',
    emoji: '🇰🇲',
    timezones: ['UTC+03:00'],
    region: 'Africa',
  ),
  Country(
    code: 'kn',
    name: 'Saint-Christophe-et-Niévès',
    dialCode: '+1869',
    iso3: 'KNA',
    currency: 'XCD',
    currencyName: 'Dollar des Caraïbes orientales',
    emoji: '🇰🇳',
    timezones: ['UTC-04:00'],
    region: 'Americas',
  ),
  Country(
    code: 'kp',
    name: 'Corée du Nord',
    dialCode: '+850',
    iso3: 'PRK',
    currency: 'KPW',
    currencyName: 'Won nord-coréen',
    emoji: '🇰🇵',
    timezones: ['UTC+09:00'],
    region: 'Asia',
  ),
  Country(
    code: 'kr',
    name: 'Corée du Sud',
    dialCode: '+82',
    iso3: 'KOR',
    currency: 'KRW',
    currencyName: 'Won sud-coréen',
    emoji: '🇰🇷',
    timezones: ['UTC+09:00'],
    region: 'Asia',
  ),
  Country(
    code: 'kw',
    name: 'Koweït',
    dialCode: '+965',
    iso3: 'KWT',
    currency: 'KWD',
    currencyName: 'Dinar koweïtien',
    emoji: '🇰🇼',
    timezones: ['UTC+03:00'],
    region: 'Asia',
  ),


  Country(
    code: 'la',
    name: 'Laos',
    dialCode: '+856',
    iso3: 'LAO',
    currency: 'LAK',
    currencyName: 'Kip laotien',
    emoji: '🇱🇦',
    timezones: ['UTC+07:00'],
    region: 'Asia',
  ),
  Country(
    code: 'lb',
    name: 'Liban',
    dialCode: '+961',
    iso3: 'LBN',
    currency: 'LBP',
    currencyName: 'Livre libanaise',
    emoji: '🇱🇧',
    timezones: ['UTC+02:00'],
    region: 'Asia',
  ),
  Country(
    code: 'lc',
    name: 'Sainte-Lucie',
    dialCode: '+1758',
    iso3: 'LCA',
    currency: 'XCD',
    currencyName: 'Dollar des Caraïbes orientales',
    emoji: '🇱🇨',
    timezones: ['UTC-04:00'],
    region: 'Americas',
  ),
  Country(
    code: 'li',
    name: 'Liechtenstein',
    dialCode: '+423',
    iso3: 'LIE',
    currency: 'CHF',
    currencyName: 'Franc suisse',
    emoji: '🇱🇮',
    timezones: ['UTC+01:00'],
    region: 'Europe',
  ),
  Country(
    code: 'lk',
    name: 'Sri Lanka',
    dialCode: '+94',
    iso3: 'LKA',
    currency: 'LKR',
    currencyName: 'Roupie srilankaise',
    emoji: '🇱🇰',
    timezones: ['UTC+05:30'],
    region: 'Asia',
  ),
  Country(
    code: 'lr',
    name: 'Libéria',
    dialCode: '+231',
    iso3: 'LBR',
    currency: 'LRD',
    currencyName: 'Dollar libérien',
    emoji: '🇱🇷',
    timezones: ['UTC'],
    region: 'Africa',
  ),
  Country(
    code: 'ls',
    name: 'Lesotho',
    dialCode: '+266',
    iso3: 'LSO',
    currency: 'LSL',
    currencyName: 'Loti lesothan',
    emoji: '🇱🇸',
    timezones: ['UTC+02:00'],
    region: 'Africa',
  ),
  Country(
    code: 'lt',
    name: 'Lituanie',
    dialCode: '+370',
    iso3: 'LTU',
    currency: 'EUR',
    currencyName: 'Euro',
    emoji: '🇱🇹',
    timezones: ['UTC+02:00'],
    region: 'Europe',
  ),
  Country(
    code: 'lu',
    name: 'Luxembourg',
    dialCode: '+352',
    iso3: 'LUX',
    currency: 'EUR',
    currencyName: 'Euro',
    emoji: '🇱🇺',
    timezones: ['UTC+01:00'],
    region: 'Europe',
  ),
  Country(
    code: 'lv',
    name: 'Lettonie',
    dialCode: '+371',
    iso3: 'LVA',
    currency: 'EUR',
    currencyName: 'Euro',
    emoji: '🇱🇻',
    timezones: ['UTC+02:00'],
    region: 'Europe',
  ),
  Country(
    code: 'ly',
    name: 'Libye',
    dialCode: '+218',
    iso3: 'LBY',
    currency: 'LYD',
    currencyName: 'Dinar libyen',
    emoji: '🇱🇾',
    timezones: ['UTC+02:00'],
    region: 'Africa',
  ),
  Country(
    code: 'ma',
    name: 'Maroc',
    dialCode: '+212',
    iso3: 'MAR',
    currency: 'MAD',
    currencyName: 'Dirham marocain',
    emoji: '🇲🇦',
    timezones: ['UTC'],
    region: 'Africa',
  ),
  Country(
    code: 'mc',
    name: 'Monaco',
    dialCode: '+377',
    iso3: 'MCO',
    currency: 'EUR',
    currencyName: 'Euro',
    emoji: '🇲🇨',
    timezones: ['UTC+01:00'],
    region: 'Europe',
  ),
  Country(
    code: 'md',
    name: 'Moldavie',
    dialCode: '+373',
    iso3: 'MDA',
    currency: 'MDL',
    currencyName: 'Leu moldave',
    emoji: '🇲🇩',
    timezones: ['UTC+02:00'],
    region: 'Europe',
  ),
  Country(
    code: 'me',
    name: 'Monténégro',
    dialCode: '+382',
    iso3: 'MNE',
    currency: 'EUR',
    currencyName: 'Euro',
    emoji: '🇲🇪',
    timezones: ['UTC+01:00'],
    region: 'Europe',
  ),
  Country(
    code: 'mg',
    name: 'Madagascar',
    dialCode: '+261',
    iso3: 'MDG',
    currency: 'MGA',
    currencyName: 'Ariary malgache',
    emoji: '🇲🇬',
    timezones: ['UTC+03:00'],
    region: 'Africa',
  ),
  Country(
    code: 'mh',
    name: 'Îles Marshall',
    dialCode: '+692',
    iso3: 'MHL',
    currency: 'USD',
    currencyName: 'Dollar américain',
    emoji: '🇲🇭',
    timezones: ['UTC+12:00'],
    region: 'Oceania',
  ),
  Country(
    code: 'mk',
    name: 'Macédoine du Nord',
    dialCode: '+389',
    iso3: 'MKD',
    currency: 'MKD',
    currencyName: 'Denar macédonien',
    emoji: '🇲🇰',
    timezones: ['UTC+01:00'],
    region: 'Europe',
  ),
  Country(
    code: 'ml',
    name: 'Mali',
    dialCode: '+223',
    iso3: 'MLI',
    currency: 'XOF',
    currencyName: 'Franc CFA (BCEAO)',
    emoji: '🇲🇱',
    timezones: ['UTC'],
    region: 'Africa',
  ),
  Country(
    code: 'mm',
    name: 'Myanmar (Birmanie)',
    dialCode: '+95',
    iso3: 'MMR',
    currency: 'MMK',
    currencyName: 'Kyat birman',
    emoji: '🇲🇲',
    timezones: ['UTC+06:30'],
    region: 'Asia',
  ),
  Country(
    code: 'mn',
    name: 'Mongolie',
    dialCode: '+976',
    iso3: 'MNG',
    currency: 'MNT',
    currencyName: 'Tugrik mongol',
    emoji: '🇲🇳',
    timezones: ['UTC+07:00', 'UTC+08:00'],
    region: 'Asia',
  ),
  Country(
    code: 'mr',
    name: 'Mauritanie',
    dialCode: '+222',
    iso3: 'MRT',
    currency: 'MRU',
    currencyName: 'Ouguiya mauritanien',
    emoji: '🇲🇷',
    timezones: ['UTC'],
    region: 'Africa',
  ),
  Country(
    code: 'mt',
    name: 'Malte',
    dialCode: '+356',
    iso3: 'MLT',
    currency: 'EUR',
    currencyName: 'Euro',
    emoji: '🇲🇹',
    timezones: ['UTC+01:00'],
    region: 'Europe',
  ),
  Country(
    code: 'mu',
    name: 'Maurice',
    dialCode: '+230',
    iso3: 'MUS',
    currency: 'MUR',
    currencyName: 'Roupie mauricienne',
    emoji: '🇲🇺',
    timezones: ['UTC+04:00'],
    region: 'Africa',
  ),
  Country(
    code: 'mv',
    name: 'Maldives',
    dialCode: '+960',
    iso3: 'MDV',
    currency: 'MVR',
    currencyName: 'Rufiyaa maldivien',
    emoji: '🇲🇻',
    timezones: ['UTC+05:00'],
    region: 'Asia',
  ),
  Country(
    code: 'mw',
    name: 'Malawi',
    dialCode: '+265',
    iso3: 'MWI',
    currency: 'MWK',
    currencyName: 'Kwacha malawite',
    emoji: '🇲🇼',
    timezones: ['UTC+02:00'],
    region: 'Africa',
  ),
  Country(
    code: 'mx',
    name: 'Mexique',
    dialCode: '+52',
    iso3: 'MEX',
    currency: 'MXN',
    currencyName: 'Peso mexicain',
    emoji: '🇲🇽',
    timezones: ['UTC-08:00', 'UTC-07:00', 'UTC-06:00'],
    region: 'Americas',
  ),
  Country(
    code: 'my',
    name: 'Malaisie',
    dialCode: '+60',
    iso3: 'MYS',
    currency: 'MYR',
    currencyName: 'Ringgit malaisien',
    emoji: '🇲🇾',
    timezones: ['UTC+08:00'],
    region: 'Asia',
  ),
  Country(
    code: 'mz',
    name: 'Mozambique',
    dialCode: '+258',
    iso3: 'MOZ',
    currency: 'MZN',
    currencyName: 'Metical mozambicain',
    emoji: '🇲🇿',
    timezones: ['UTC+02:00'],
    region: 'Africa',
  ),
  Country(
    code: 'na',
    name: 'Namibie',
    dialCode: '+264',
    iso3: 'NAM',
    currency: 'NAD',
    currencyName: 'Dollar namibien',
    emoji: '🇳🇦',
    timezones: ['UTC+01:00'],
    region: 'Africa',
  ),
  Country(
    code: 'ne',
    name: 'Niger',
    dialCode: '+227',
    iso3: 'NER',
    currency: 'XOF',
    currencyName: 'Franc CFA (BCEAO)',
    emoji: '🇳🇪',
    timezones: ['UTC+01:00'],
    region: 'Africa',
  ),
  Country(
    code: 'ng',
    name: 'Nigéria',
    dialCode: '+234',
    iso3: 'NGA',
    currency: 'NGN',
    currencyName: 'Naira nigérian',
    emoji: '🇳🇬',
    timezones: ['UTC+01:00'],
    region: 'Africa',
  ),
  Country(
    code: 'ni',
    name: 'Nicaragua',
    dialCode: '+505',
    iso3: 'NIC',
    currency: 'NIO',
    currencyName: 'Córdoba oro',
    emoji: '🇳🇮',
    timezones: ['UTC-06:00'],
    region: 'Americas',
  ),
  Country(
    code: 'nl',
    name: 'Pays-Bas',
    dialCode: '+31',
    iso3: 'NLD',
    currency: 'EUR',
    currencyName: 'Euro',
    emoji: '🇳🇱',
    timezones: ['UTC+01:00'],
    region: 'Europe',
  ),
  Country(
    code: 'no',
    name: 'Norvège',
    dialCode: '+47',
    iso3: 'NOR',
    currency: 'NOK',
    currencyName: 'Couronne norvégienne',
    emoji: '🇳🇴',
    timezones: ['UTC+01:00'],
    region: 'Europe',
  ),
  Country(
    code: 'np',
    name: 'Népal',
    dialCode: '+977',
    iso3: 'NPL',
    currency: 'NPR',
    currencyName: 'Roupie népalaise',
    emoji: '🇳🇵',
    timezones: ['UTC+05:45'],
    region: 'Asia',
  ),
  Country(
    code: 'nr',
    name: 'Nauru',
    dialCode: '+674',
    iso3: 'NRU',
    currency: 'AUD',
    currencyName: 'Dollar australien',
    emoji: '🇳🇷',
    timezones: ['UTC+12:00'],
    region: 'Oceania',
  ),
  Country(
    code: 'nz',
    name: 'Nouvelle-Zélande',
    dialCode: '+64',
    iso3: 'NZL',
    currency: 'NZD',
    currencyName: 'Dollar néo-zélandais',
    emoji: '🇳🇿',
    timezones: ['UTC+12:00', 'UTC+13:00'],
    region: 'Oceania',
  ),
  Country(
    code: 'om',
    name: 'Oman',
    dialCode: '+968',
    iso3: 'OMN',
    currency: 'OMR',
    currencyName: 'Rial omanais',
    emoji: '🇴🇲',
    timezones: ['UTC+04:00'],
    region: 'Asia',
  ),
  Country(
    code: 'pa',
    name: 'Panama',
    dialCode: '+507',
    iso3: 'PAN',
    currency: 'PAB',
    currencyName: 'Balboa panaméen',
    emoji: '🇵🇦',
    timezones: ['UTC-05:00'],
    region: 'Americas',
  ),
  Country(
    code: 'pe',
    name: 'Pérou',
    dialCode: '+51',
    iso3: 'PER',
    currency: 'PEN',
    currencyName: 'Sol péruvien',
    emoji: '🇵🇪',
    timezones: ['UTC-05:00'],
    region: 'Americas',
  ),
  Country(
    code: 'pg',
    name: 'Papouasie-Nouvelle-Guinée',
    dialCode: '+675',
    iso3: 'PNG',
    currency: 'PGK',
    currencyName: 'Kina papouasien',
    emoji: '🇵🇬',
    timezones: ['UTC+10:00', 'UTC+11:00'],
    region: 'Oceania',
  ),
  Country(
    code: 'ph',
    name: 'Philippines',
    dialCode: '+63',
    iso3: 'PHL',
    currency: 'PHP',
    currencyName: 'Peso philippin',
    emoji: '🇵🇭',
    timezones: ['UTC+08:00'],
    region: 'Asia',
  ),
  Country(
    code: 'pk',
    name: 'Pakistan',
    dialCode: '+92',
    iso3: 'PAK',
    currency: 'PKR',
    currencyName: 'Roupie pakistanaise',
    emoji: '🇵🇰',
    timezones: ['UTC+05:00'],
    region: 'Asia',
  ),
  Country(
    code: 'pl',
    name: 'Pologne',
    dialCode: '+48',
    iso3: 'POL',
    currency: 'PLN',
    currencyName: 'Złoty polonais',
    emoji: '🇵🇱',
    timezones: ['UTC+01:00'],
    region: 'Europe',
  ),
  Country(
    code: 'pt',
    name: 'Portugal',
    dialCode: '+351',
    iso3: 'PRT',
    currency: 'EUR',
    currencyName: 'Euro',
    emoji: '🇵🇹',
    timezones: ['UTC', 'UTC+01:00'],
    region: 'Europe',
  ),
  Country(
    code: 'pw',
    name: 'Palaos',
    dialCode: '+680',
    iso3: 'PLW',
    currency: 'USD',
    currencyName: 'Dollar américain',
    emoji: '🇵🇼',
    timezones: ['UTC+09:00'],
    region: 'Oceania',
  ),
  Country(
    code: 'py',
    name: 'Paraguay',
    dialCode: '+595',
    iso3: 'PRY',
    currency: 'PYG',
    currencyName: 'Guaraní paraguayen',
    emoji: '🇵🇾',
    timezones: ['UTC-04:00'],
    region: 'Americas',
  ),
  Country(
    code: 'qa',
    name: 'Qatar',
    dialCode: '+974',
    iso3: 'QAT',
    currency: 'QAR',
    currencyName: 'Rial qatari',
    emoji: '🇶🇦',
    timezones: ['UTC+03:00'],
    region: 'Asia',
  ),
  Country(
    code: 'ro',
    name: 'Roumanie',
    dialCode: '+40',
    iso3: 'ROU',
    currency: 'RON',
    currencyName: 'Leu roumain',
    emoji: '🇷🇴',
    timezones: ['UTC+02:00'],
    region: 'Europe',
  ),
  Country(
    code: 'rs',
    name: 'Serbie',
    dialCode: '+381',
    iso3: 'SRB',
    currency: 'RSD',
    currencyName: 'Dinar serbe',
    emoji: '🇷🇸',
    timezones: ['UTC+01:00'],
    region: 'Europe',
  ),
  Country(
    code: 'ru',
    name: 'Russie',
    dialCode: '+7',
    iso3: 'RUS',
    currency: 'RUB',
    currencyName: 'Rouble russe',
    emoji: '🇷🇺',
    timezones: ['UTC+02:00', 'UTC+12:00'],
    region: 'Europe/Asia',
  ),
  Country(
    code: 'rw',
    name: 'Rwanda',
    dialCode: '+250',
    iso3: 'RWA',
    currency: 'RWF',
    currencyName: 'Franc rwandais',
    emoji: '🇷🇼',
    timezones: ['UTC+02:00'],
    region: 'Africa',
  ),
  Country(
    code: 'sa',
    name: 'Arabie Saoudite',
    dialCode: '+966',
    iso3: 'SAU',
    currency: 'SAR',
    currencyName: 'Riyal saoudien',
    emoji: '🇸🇦',
    timezones: ['UTC+03:00'],
    region: 'Asia',
  ),
  Country(
    code: 'sb',
    name: 'Îles Salomon',
    dialCode: '+677',
    iso3: 'SLB',
    currency: 'SBD',
    currencyName: 'Dollar des Îles Salomon',
    emoji: '🇸🇧',
    timezones: ['UTC+11:00'],
    region: 'Oceania',
  ),
  Country(
    code: 'sc',
    name: 'Seychelles',
    dialCode: '+248',
    iso3: 'SYC',
    currency: 'SCR',
    currencyName: 'Roupie seychelloise',
    emoji: '🇸🇨',
    timezones: ['UTC+04:00'],
    region: 'Africa',
  ),
  Country(
    code: 'sd',
    name: 'Soudan',
    dialCode: '+249',
    iso3: 'SDN',
    currency: 'SDG',
    currencyName: 'Livre soudanaise',
    emoji: '🇸🇩',
    timezones: ['UTC+03:00'],
    region: 'Africa',
  ),
  Country(
    code: 'se',
    name: 'Suède',
    dialCode: '+46',
    iso3: 'SWE',
    currency: 'SEK',
    currencyName: 'Couronne suédoise',
    emoji: '🇸🇪',
    timezones: ['UTC+01:00'],
    region: 'Europe',
  ),
  Country(
    code: 'sg',
    name: 'Singapour',
    dialCode: '+65',
    iso3: 'SGP',
    currency: 'SGD',
    currencyName: 'Dollar de Singapour',
    emoji: '🇸🇬',
    timezones: ['UTC+08:00'],
    region: 'Asia',
  ),
  Country(
    code: 'si',
    name: 'Slovénie',
    dialCode: '+386',
    iso3: 'SVN',
    currency: 'EUR',
    currencyName: 'Euro',
    emoji: '🇸🇮',
    timezones: ['UTC+01:00'],
    region: 'Europe',
  ),
  Country(
    code: 'sk',
    name: 'Slovaquie',
    dialCode: '+421',
    iso3: 'SVK',
    currency: 'EUR',
    currencyName: 'Euro',
    emoji: '🇸🇰',
    timezones: ['UTC+01:00'],
    region: 'Europe',
  ),
  Country(
    code: 'sl',
    name: 'Sierra Leone',
    dialCode: '+232',
    iso3: 'SLE',
    currency: 'SLL',
    currencyName: 'Leone sierra-léonais',
    emoji: '🇸🇱',
    timezones: ['UTC'],
    region: 'Africa',
  ),
  Country(
    code: 'sm',
    name: 'Saint-Marin',
    dialCode: '+378',
    iso3: 'SMR',
    currency: 'EUR',
    currencyName: 'Euro',
    emoji: '🇸🇲',
    timezones: ['UTC+01:00'],
    region: 'Europe',
  ),
  Country(
    code: 'sn',
    name: 'Sénégal',
    dialCode: '+221',
    iso3: 'SEN',
    currency: 'XOF',
    currencyName: 'Franc CFA (BCEAO)',
    emoji: '🇸🇳',
    timezones: ['UTC'],
    region: 'Africa',
  ),
  Country(
    code: 'so',
    name: 'Somalie',
    dialCode: '+252',
    iso3: 'SOM',
    currency: 'SOS',
    currencyName: 'Shilling somalien',
    emoji: '🇸🇴',
    timezones: ['UTC+03:00'],
    region: 'Africa',
  ),
  Country(
    code: 'sr',
    name: 'Suriname',
    dialCode: '+597',
    iso3: 'SUR',
    currency: 'SRD',
    currencyName: 'Dollar surinamais',
    emoji: '🇸🇷',
    timezones: ['UTC-03:00'],
    region: 'Americas',
  ),
  Country(
    code: 'ss',
    name: 'Soudan du Sud',
    dialCode: '+211',
    iso3: 'SSD',
    currency: 'SSP',
    currencyName: 'Livre sud-soudanaise',
    emoji: '🇸🇸',
    timezones: ['UTC+03:00'],
    region: 'Africa',
  ),
  Country(
    code: 'st',
    name: 'Sao Tomé-et-Principe',
    dialCode: '+239',
    iso3: 'STP',
    currency: 'STN',
    currencyName: 'Dobra',
    emoji: '🇸🇹',
    timezones: ['UTC'],
    region: 'Africa',
  ),
  Country(
    code: 'sv',
    name: 'Salvador',
    dialCode: '+503',
    iso3: 'SLV',
    currency: 'USD',
    currencyName: 'Dollar américain',
    emoji: '🇸🇻',
    timezones: ['UTC-06:00'],
    region: 'Americas',
  ),
  Country(
    code: 'sy',
    name: 'Syrie',
    dialCode: '+963',
    iso3: 'SYR',
    currency: 'SYP',
    currencyName: 'Livre syrienne',
    emoji: '🇸🇾',
    timezones: ['UTC+02:00'],
    region: 'Asia',
  ),
  Country(
    code: 'sz',
    name: 'Eswatini',
    dialCode: '+268',
    iso3: 'SWZ',
    currency: 'SZL',
    currencyName: 'Lilangeni',
    emoji: '🇸🇿',
    timezones: ['UTC+02:00'],
    region: 'Africa',
  ),
  Country(
    code: 'td',
    name: 'Tchad',
    dialCode: '+235',
    iso3: 'TCD',
    currency: 'XAF',
    currencyName: 'Franc CFA (BEAC)',
    emoji: '🇹🇩',
    timezones: ['UTC+01:00'],
    region: 'Africa',
  ),
  Country(
    code: 'tg',
    name: 'Togo',
    dialCode: '+228',
    iso3: 'TGO',
    currency: 'XOF',
    currencyName: 'Franc CFA (BCEAO)',
    emoji: '🇹🇬',
    timezones: ['UTC'],
    region: 'Africa',
  ),
  Country(
    code: 'th',
    name: 'Thaïlande',
    dialCode: '+66',
    iso3: 'THA',
    currency: 'THB',
    currencyName: 'Baht thaïlandais',
    emoji: '🇹🇭',
    timezones: ['UTC+07:00'],
    region: 'Asia',
  ),
  Country(
    code: 'tj',
    name: 'Tadjikistan',
    dialCode: '+992',
    iso3: 'TJK',
    currency: 'TJS',
    currencyName: 'Somoni tadjik',
    emoji: '🇹🇯',
    timezones: ['UTC+05:00'],
    region: 'Asia',
  ),
  Country(
    code: 'tl',
    name: 'Timor oriental',
    dialCode: '+670',
    iso3: 'TLS',
    currency: 'USD',
    currencyName: 'Dollar américain',
    emoji: '🇹🇱',
    timezones: ['UTC+09:00'],
    region: 'Asia',
  ),
  Country(
    code: 'tm',
    name: 'Turkménistan',
    dialCode: '+993',
    iso3: 'TKM',
    currency: 'TMT',
    currencyName: 'Manat turkmène',
    emoji: '🇹🇲',
    timezones: ['UTC+05:00'],
    region: 'Asia',
  ),
  Country(
    code: 'tn',
    name: 'Tunisie',
    dialCode: '+216',
    iso3: 'TUN',
    currency: 'TND',
    currencyName: 'Dinar tunisien',
    emoji: '🇹🇳',
    timezones: ['UTC+01:00'],
    region: 'Africa',
  ),
  Country(
    code: 'to',
    name: 'Tonga',
    dialCode: '+676',
    iso3: 'TON',
    currency: 'TOP',
    currencyName: 'Paʻanga',
    emoji: '🇹🇴',
    timezones: ['UTC+13:00'],
    region: 'Oceania',
  ),
  Country(
    code: 'tr',
    name: 'Turquie',
    dialCode: '+90',
    iso3: 'TUR',
    currency: 'TRY',
    currencyName: 'Lire turque',
    emoji: '🇹🇷',
    timezones: ['UTC+03:00'],
    region: 'Asia',
  ),
  Country(
    code: 'tt',
    name: 'Trinité-et-Tobago',
    dialCode: '+1868',
    iso3: 'TTO',
    currency: 'TTD',
    currencyName: 'Dollar de Trinité-et-Tobago',
    emoji: '🇹🇹',
    timezones: ['UTC-04:00'],
    region: 'Americas',
  ),
  Country(
    code: 'tv',
    name: 'Tuvalu',
    dialCode: '+688',
    iso3: 'TUV',
    currency: 'AUD',
    currencyName: 'Dollar australien',
    emoji: '🇹🇻',
    timezones: ['UTC+12:00'],
    region: 'Oceania',
  ),
  Country(
    code: 'tz',
    name: 'Tanzanie',
    dialCode: '+255',
    iso3: 'TZA',
    currency: 'TZS',
    currencyName: 'Shilling tanzanien',
    emoji: '🇹🇿',
    timezones: ['UTC+03:00'],
    region: 'Africa',
  ),
  Country(
    code: 'ua',
    name: 'Ukraine',
    dialCode: '+380',
    iso3: 'UKR',
    currency: 'UAH',
    currencyName: 'Hryvnia',
    emoji: '🇺🇦',
    timezones: ['UTC+02:00'],
    region: 'Europe',
  ),
  Country(
    code: 'ug',
    name: 'Ouganda',
    dialCode: '+256',
    iso3: 'UGA',
    currency: 'UGX',
    currencyName: 'Shilling ougandais',
    emoji: '🇺🇬',
    timezones: ['UTC+03:00'],
    region: 'Africa',
  ),
  Country(
    code: 'us',
    name: 'États-Unis',
    dialCode: '+1',
    iso3: 'USA',
    currency: 'USD',
    currencyName: 'Dollar américain',
    emoji: '🇺🇸',
    timezones: ['UTC-12:00', 'UTC+12:00'],
    region: 'Americas',
  ),
  Country(
    code: 'uy',
    name: 'Uruguay',
    dialCode: '+598',
    iso3: 'URY',
    currency: 'UYU',
    currencyName: 'Peso uruguayen',
    emoji: '🇺🇾',
    timezones: ['UTC-03:00'],
    region: 'Americas',
  ),
  Country(
    code: 'uz',
    name: 'Ouzbékistan',
    dialCode: '+998',
    iso3: 'UZB',
    currency: 'UZS',
    currencyName: 'Sum ouzbek',
    emoji: '🇺🇿',
    timezones: ['UTC+05:00'],
    region: 'Asia',
  ),
  Country(
    code: 'va',
    name: 'Vatican',
    dialCode: '+379',
    iso3: 'VAT',
    currency: 'EUR',
    currencyName: 'Euro',
    emoji: '🇻🇦',
    timezones: ['UTC+01:00'],
    region: 'Europe',
  ),
  Country(
    code: 'vc',
    name: 'Saint-Vincent-et-les-Grenadines',
    dialCode: '+1784',
    iso3: 'VCT',
    currency: 'XCD',
    currencyName: 'Dollar des Caraïbes orientales',
    emoji: '🇻🇨',
    timezones: ['UTC-04:00'],
    region: 'Americas',
  ),
  Country(
    code: 've',
    name: 'Venezuela',
    dialCode: '+58',
    iso3: 'VEN',
    currency: 'VES',
    currencyName: 'Bolívar souverain',
    emoji: '🇻🇪',
    timezones: ['UTC-04:00'],
    region: 'Americas',
  ),
  Country(
    code: 'vn',
    name: 'Vietnam',
    dialCode: '+84',
    iso3: 'VNM',
    currency: 'VND',
    currencyName: 'Dồng',
    emoji: '🇻🇳',
    timezones: ['UTC+07:00'],
    region: 'Asia',
  ),
  Country(
    code: 'vu',
    name: 'Vanuatu',
    dialCode: '+678',
    iso3: 'VUT',
    currency: 'VUV',
    currencyName: 'Vatu',
    emoji: '🇻🇺',
    timezones: ['UTC+11:00'],
    region: 'Oceania',
  ),
  Country(
    code: 'ws',
    name: 'Samoa',
    dialCode: '+685',
    iso3: 'WSM',
    currency: 'WST',
    currencyName: 'Tala',
    emoji: '🇼🇸',
    timezones: ['UTC+13:00'],
    region: 'Oceania',
  ),
  Country(
    code: 'ye',
    name: 'Yémen',
    dialCode: '+967',
    iso3: 'YEM',
    currency: 'YER',
    currencyName: 'Rial yéménite',
    emoji: '🇾🇪',
    timezones: ['UTC+03:00'],
    region: 'Asia',
  ),
  Country(
    code: 'za',
    name: 'Afrique du Sud',
    dialCode: '+27',
    iso3: 'ZAF',
    currency: 'ZAR',
    currencyName: 'Rand sud-africain',
    emoji: '🇿🇦',
    timezones: ['UTC+02:00'],
    region: 'Africa',
  ),
  Country(
    code: 'zm',
    name: 'Zambie',
    dialCode: '+260',
    iso3: 'ZMB',
    currency: 'ZMW',
    currencyName: 'Kwacha zambien',
    emoji: '🇿🇲',
    timezones: ['UTC+02:00'],
    region: 'Africa',
  ),
  Country(
    code: 'zw',
    name: 'Zimbabwe',
    dialCode: '+263',
    iso3: 'ZWE',
    currency: 'ZWL',
    currencyName: 'Dollar zimbabwéen',
    emoji: '🇿🇼',
    timezones: ['UTC+02:00'],
    region: 'Africa',
  ),

];

