class Country {
  final String code;
  final String name;
  final String dialCode;
  final String iso3;
  final String currency;
  final String currencyName;
  final String emoji;
  final List<String> timezones;
  final String region;
  final Map<String, String> translations;

  const Country({
    required this.code,
    required this.name,
    required this.dialCode,
    required this.iso3,
    required this.currency,
    required this.currencyName,
    required this.emoji,
    required this.timezones,
    required this.region,
    required this.translations,
  });

  String getName([String languageCode = 'es']) {
    return translations[languageCode] ?? name;
  }

  @override
  bool operator ==(Object other) =>
      identical(this, other) || other is Country && code == other.code;

  @override
  int get hashCode => code.hashCode;

  Map<String, dynamic> toMap() {
    return {
      'code': code,
      'name': name,
      'dialCode': dialCode,
      'iso3': iso3,
      'currency': currency,
      'currencyName': currencyName,
      'emoji': emoji,
      'timezones': timezones,
      'region': region,
      'translations': translations,
    };
  }
}

const List<Country> defaultCountries = [
  Country(
    code: 'af',
    name: 'Afghanistan',
    dialCode: '+93',
    iso3: 'AFG',
    currency: 'AFN',
    currencyName: 'Afghan Afghani',
    emoji: '🇦🇫',
    timezones: ['UTC+04:30'],
    region: 'Asia',
    translations: {
      'en': 'Afghanistan',
      'ru': 'Афганистан',
      'pl': 'Afganistan',
      'ua': 'Афганістан',
      'cz': 'Afghánistán',
      'by': 'Афганістан',
      'pt': 'Afeganistão',
      'es': 'Afganistán',
      'ro': 'Afganistan',
      'bg': 'Афганистан',
      'de': 'Afghanistan',
      'fr': 'Afghanistan',
      'nl': 'Afghanistan',
      'it': 'Afghanistan',
      'cn': '阿富汗',
      'ee': 'Afganistan',
      'jp': 'アフガニスタン',
      'he': 'אפגניסטן',
      'tr': 'Afganistan',
      'ar': 'أفغانستان',
    },
  ),
  Country(
    code: 'al',
    name: 'Albania',
    dialCode: '+355',
    iso3: 'ALB',
    currency: 'ALL',
    currencyName: 'Albanian Lek',
    emoji: '🇦🇱',
    timezones: ['UTC+01:00'],
    region: 'Europe',
    translations: {
      'en': 'Albania',
      'ru': 'Албания',
      'pl': 'Albania',
      'ua': 'Албанія',
      'cz': 'Albánie',
      'by': 'Албанія',
      'pt': 'Albânia',
      'es': 'Albania',
      'ro': 'Albania',
      'bg': 'Албания',
      'de': 'Albanien',
      'fr': 'Albanie',
      'nl': 'Albanië',
      'it': 'Albania',
      'cn': '阿尔巴尼亚',
      'ee': 'Albaania',
      'jp': 'アルバニア',
      'he': 'אלבניה',
      'tr': 'Arnavutluk',
      'ar': 'ألبانيا',
    },
  ),
  Country(
    code: 'dz',
    name: 'Algeria',
    dialCode: '+213',
    iso3: 'DZA',
    currency: 'DZD',
    currencyName: 'Algerian Dinar',
    emoji: '🇩🇿',
    timezones: ['UTC+01:00'],
    region: 'Africa',
    translations: {
      'en': 'Algeria',
      'ru': 'Алжир',
      'pl': 'Algieria',
      'ua': 'Алжир',
      'cz': 'Alžírsko',
      'by': 'Алжыр',
      'pt': 'Argélia',
      'es': 'Argelia',
      'ro': 'Algeria',
      'bg': 'Алжир',
      'de': 'Algerien',
      'fr': 'Algérie',
      'nl': 'Algerije',
      'it': 'Algeria',
      'cn': '阿尔及利亚',
      'ee': 'Alžeeria',
      'jp': 'アルジェリア',
      'he': 'אלג׳יריה',
      'tr': 'Cezayir',
      'ar': 'الجزائر',
    },
  ),
  Country(
    code: 'as',
    name: 'American Samoa',
    dialCode: '+1684',
    iso3: 'ASM',
    currency: 'USD',
    currencyName: 'US Dollar',
    emoji: '🇦🇸',
    timezones: ['UTC-11:00'],
    region: 'Oceania',
    translations: {
      'en': 'American Samoa',
      'ru': 'Американское Самоа',
      'pl': 'Samoa Amerykańskie',
      'ua': 'Американське Самоа',
      'cz': 'Americká Samoa',
      'by': 'Амерыканскае Самоа',
      'pt': 'Samoa Americana',
      'es': 'Samoa Americana',
      'ro': 'Samoa Americană',
      'bg': 'Американска Самоа',
      'de': 'Amerikanisch-Samoa',
      'fr': 'Samoa américaines',
      'nl': 'Amerikaans-Samoa',
      'it': 'Samoa Americane',
      'cn': '美属萨摩亚',
      'ee': 'Ameerika Samoa',
      'jp': 'アメリカ領サモア',
      'he': 'סמואה האמריקנית',
      'tr': 'Amerikan Samoası',
      'ar': 'ساموا الأمريكية',
    },
  ),
  Country(
    code: 'ad',
    name: 'Andorra',
    dialCode: '+376',
    iso3: 'AND',
    currency: 'EUR',
    currencyName: 'Euro',
    emoji: '🇦🇩',
    timezones: ['UTC+01:00'],
    region: 'Europe',
    translations: {
      'en': 'Andorra',
      'ru': 'Андорра',
      'pl': 'Andora',
      'ua': 'Андорра',
      'cz': 'Andorra',
      'by': 'Андора',
      'pt': 'Andorra',
      'es': 'Andorra',
      'ro': 'Andorra',
      'bg': 'Андора',
      'de': 'Andorra',
      'fr': 'Andorre',
      'nl': 'Andorra',
      'it': 'Andorra',
      'cn': '安道尔',
      'ee': 'Andorra',
      'jp': 'アンドラ',
      'he': 'אנדורה',
      'tr': 'Andorra',
      'ar': 'أندورا',
    },
  ),
  Country(
    code: 'ao',
    name: 'Angola',
    dialCode: '+244',
    iso3: 'AGO',
    currency: 'AOA',
    currencyName: 'Angolan Kwanza',
    emoji: '🇦🇴',
    timezones: ['UTC+01:00'],
    region: 'Africa',
    translations: {
      'en': 'Angola',
      'ru': 'Ангола',
      'pl': 'Angola',
      'ua': 'Ангола',
      'cz': 'Angola',
      'by': 'Ангола',
      'pt': 'Angola',
      'es': 'Angola',
      'ro': 'Angola',
      'bg': 'Ангола',
      'de': 'Angola',
      'fr': 'Angola',
      'nl': 'Angola',
      'it': 'Angola',
      'cn': '安哥拉',
      'ee': 'Angola',
      'jp': 'アンゴラ',
      'he': 'אנגולה',
      'tr': 'Angola',
      'ar': 'أنغولا',
    },
  ),
  Country(
    code: 'ai',
    name: 'Anguilla',
    dialCode: '+1264',
    iso3: 'AIA',
    currency: 'XCD',
    currencyName: 'East Caribbean Dollar',
    emoji: '🇦🇮',
    timezones: ['UTC-04:00'],
    region: 'Americas',
    translations: {
      'en': 'Anguilla',
      'ru': 'Ангилья',
      'pl': 'Anguilla',
      'ua': 'Ангілья',
      'cz': 'Anguilla',
      'by': 'Ангілья',
      'pt': 'Anguila',
      'es': 'Anguila',
      'ro': 'Anguilla',
      'bg': 'Ангуила',
      'de': 'Anguilla',
      'fr': 'Anguilla',
      'nl': 'Anguilla',
      'it': 'Anguilla',
      'cn': '安圭拉',
      'ee': 'Anguilla',
      'jp': 'アンギラ',
      'he': 'אנגילה',
      'tr': 'Anguilla',
      'ar': 'أنغويلا',
    },
  ),
  Country(
    code: 'ag',
    name: 'Antigua and Barbuda',
    dialCode: '+1268',
    iso3: 'ATG',
    currency: 'XCD',
    currencyName: 'East Caribbean Dollar',
    emoji: '🇦🇬',
    timezones: ['UTC-04:00'],
    region: 'Americas',
    translations: {
      'en': 'Antigua and Barbuda',
      'ru': 'Антигуа и Барбуда',
      'pl': 'Antigua i Barbuda',
      'ua': 'Антигуа і Барбуда',
      'cz': 'Antigua a Barbuda',
      'by': 'Антыгуа і Барбуда',
      'pt': 'Antígua e Barbuda',
      'es': 'Antigua y Barbuda',
      'ro': 'Antigua și Barbuda',
      'bg': 'Антигуа и Барбуда',
      'de': 'Antigua und Barbuda',
      'fr': 'Antigua-et-Barbuda',
      'nl': 'Antigua en Barbuda',
      'it': 'Antigua e Barbuda',
      'cn': '安提瓜和巴布达',
      'ee': 'Antigua ja Barbuda',
      'jp': 'アンティグア・バーブーダ',
      'he': 'אנטיגואה וברבודה',
      'tr': 'Antigua ve Barbuda',
      'ar': 'أنتيغوا وباربودا',
    },
  ),
  Country(
    code: 'ar',
    name: 'Argentina',
    dialCode: '+54',
    iso3: 'ARG',
    currency: 'ARS',
    currencyName: 'Argentine Peso',
    emoji: '🇦🇷',
    timezones: ['UTC-03:00'],
    region: 'Americas',
    translations: {
      'en': 'Argentina',
      'ru': 'Аргентина',
      'pl': 'Argentyna',
      'ua': 'Аргентина',
      'cz': 'Argentina',
      'by': 'Аргенціна',
      'pt': 'Argentina',
      'es': 'Argentina',
      'ro': 'Argentina',
      'bg': 'Аржентина',
      'de': 'Argentinien',
      'fr': 'Argentine',
      'nl': 'Argentinië',
      'it': 'Argentina',
      'cn': '阿根廷',
      'ee': 'Argentina',
      'jp': 'アルゼンチン',
      'he': 'ארגנטינה',
      'tr': 'Arjantin',
      'ar': 'الأرجنتين',
    },
  ),
  Country(
    code: 'am',
    name: 'Armenia',
    dialCode: '+374',
    iso3: 'ARM',
    currency: 'AMD',
    currencyName: 'Armenian Dram',
    emoji: '🇦🇲',
    timezones: ['UTC+04:00'],
    region: 'Asia',
    translations: {
      'en': 'Armenia',
      'ru': 'Армения',
      'pl': 'Armenia',
      'ua': 'Вірменія',
      'cz': 'Arménie',
      'by': 'Арменія',
      'pt': 'Arménia',
      'es': 'Armenia',
      'ro': 'Armenia',
      'bg': 'Армения',
      'de': 'Armenien',
      'fr': 'Arménie',
      'nl': 'Armenië',
      'it': 'Armenia',
      'cn': '亚美尼亚',
      'ee': 'Armeenia',
      'jp': 'アルメニア',
      'he': 'ארמניה',
      'tr': 'Ermenistan',
      'ar': 'أرمينيا',
    },
  ),
  Country(
    code: 'aw',
    name: 'Aruba',
    dialCode: '+297',
    iso3: 'ABW',
    currency: 'AWG',
    currencyName: 'Aruban Florin',
    emoji: '🇦🇼',
    timezones: ['UTC-04:00'],
    region: 'Americas',
    translations: {
      'en': 'Aruba',
      'ru': 'Аруба',
      'pl': 'Aruba',
      'ua': 'Аруба',
      'cz': 'Aruba',
      'by': 'Аруба',
      'pt': 'Aruba',
      'es': 'Aruba',
      'ro': 'Aruba',
      'bg': 'Аруба',
      'de': 'Aruba',
      'fr': 'Aruba',
      'nl': 'Aruba',
      'it': 'Aruba',
      'cn': '阿鲁巴',
      'ee': 'Aruba',
      'jp': 'アルバ',
      'he': 'ארובה',
      'tr': 'Aruba',
      'ar': 'أروبا',
    },
  ),
  Country(
    code: 'au',
    name: 'Australia',
    dialCode: '+61',
    iso3: 'AUS',
    currency: 'AUD',
    currencyName: 'Australian Dollar',
    emoji: '🇦🇺',
    timezones: ['UTC+08:00', 'UTC+09:30', 'UTC+10:00', 'UTC+10:30', 'UTC+11:00'],
    region: 'Oceania',
    translations: {
      'en': 'Australia',
      'ru': 'Австралия',
      'pl': 'Australia',
      'ua': 'Австралія',
      'cz': 'Austrálie',
      'by': 'Аўстралія',
      'pt': 'Austrália',
      'es': 'Australia',
      'ro': 'Australia',
      'bg': 'Австралия',
      'de': 'Australien',
      'fr': 'Australie',
      'nl': 'Australië',
      'it': 'Australia',
      'cn': '澳大利亚',
      'ee': 'Austraalia',
      'jp': 'オーストラリア',
      'he': 'אוסטרליה',
      'tr': 'Avustralya',
      'ar': 'أستراليا',
    },
  ),
  Country(
    code: 'at',
    name: 'Austria',
    dialCode: '+43',
    iso3: 'AUT',
    currency: 'EUR',
    currencyName: 'Euro',
    emoji: '🇦🇹',
    timezones: ['UTC+01:00'],
    region: 'Europe',
    translations: {
      'en': 'Austria',
      'ru': 'Австрия',
      'pl': 'Austria',
      'ua': 'Австрія',
      'cz': 'Rakousko',
      'by': 'Аўстрыя',
      'pt': 'Áustria',
      'es': 'Austria',
      'ro': 'Austria',
      'bg': 'Австрия',
      'de': 'Österreich',
      'fr': 'Autriche',
      'nl': 'Oostenrijk',
      'it': 'Austria',
      'cn': '奥地利',
      'ee': 'Austria',
      'jp': 'オーストリア',
      'he': 'אוסטריה',
      'tr': 'Avusturya',
      'ar': 'النمسا',
    },
  ),
  Country(
    code: 'az',
    name: 'Azerbaijan',
    dialCode: '+994',
    iso3: 'AZE',
    currency: 'AZN',
    currencyName: 'Azerbaijani Manat',
    emoji: '🇦🇿',
    timezones: ['UTC+04:00'],
    region: 'Asia',
    translations: {
      'en': 'Azerbaijan',
      'ru': 'Азербайджан',
      'pl': 'Azerbejdżan',
      'ua': 'Азербайджан',
      'cz': 'Ázerbájdžán',
      'by': 'Азербайджан',
      'pt': 'Azerbaijão',
      'es': 'Azerbaiyán',
      'ro': 'Azerbaidjan',
      'bg': 'Азербайджан',
      'de': 'Aserbaidschan',
      'fr': 'Azerbaïdjan',
      'nl': 'Azerbeidzjan',
      'it': 'Azerbaigian',
      'cn': '阿塞拜疆',
      'ee': 'Aserbaidžaan',
      'jp': 'アゼルバイジャン',
      'he': 'אזרבייג׳ן',
      'tr': 'Azerbaycan',
      'ar': 'أذربيجان',
    },
  ),
  Country(
    code: 'bs',
    name: 'Bahamas',
    dialCode: '+1242',
    iso3: 'BHS',
    currency: 'BSD',
    currencyName: 'Bahamian Dollar',
    emoji: '🇧🇸',
    timezones: ['UTC-05:00'],
    region: 'Americas',
    translations: {
      'en': 'Bahamas',
      'ru': 'Багамские Острова',
      'pl': 'Bahamy',
      'ua': 'Багамські Острови',
      'cz': 'Bahamy',
      'by': 'Багамы',
      'pt': 'Bahamas',
      'es': 'Bahamas',
      'ro': 'Bahamas',
      'bg': 'Бахамски острови',
      'de': 'Bahamas',
      'fr': 'Bahamas',
      'nl': 'Bahama\'s',
      'it': 'Bahamas',
      'cn': '巴哈马',
      'ee': 'Bahama',
      'jp': 'バハマ',
      'he': 'איי בהאמה',
      'tr': 'Bahamalar',
      'ar': 'باهاماس',
    },
  ),
  Country(
    code: 'bh',
    name: 'Bahrain',
    dialCode: '+973',
    iso3: 'BHR',
    currency: 'BHD',
    currencyName: 'Bahraini Dinar',
    emoji: '🇧🇭',
    timezones: ['UTC+03:00'],
    region: 'Asia',
    translations: {
      'en': 'Bahrain',
      'ru': 'Бахрейн',
      'pl': 'Bahrajn',
      'ua': 'Бахрейн',
      'cz': 'Bahrajn',
      'by': 'Бахрэйн',
      'pt': 'Bahrein',
      'es': 'Baréin',
      'ro': 'Bahrain',
      'bg': 'Бахрейн',
      'de': 'Bahrain',
      'fr': 'Bahreïn',
      'nl': 'Bahrein',
      'it': 'Bahrein',
      'cn': '巴林',
      'ee': 'Bahrein',
      'jp': 'バーレーン',
      'he': 'בחריין',
      'tr': 'Bahreyn',
      'ar': 'البحرين',
    },
  ),
  Country(
    code: 'bd',
    name: 'Bangladesh',
    dialCode: '+880',
    iso3: 'BGD',
    currency: 'BDT',
    currencyName: 'Bangladeshi Taka',
    emoji: '🇧🇩',
    timezones: ['UTC+06:00'],
    region: 'Asia',
    translations: {
      'en': 'Bangladesh',
      'ru': 'Бангладеш',
      'pl': 'Bangladesz',
      'ua': 'Бангладеш',
      'cz': 'Bangladéš',
      'by': 'Бангладэш',
      'pt': 'Bangladesh',
      'es': 'Bangladés',
      'ro': 'Bangladesh',
      'bg': 'Бангладеш',
      'de': 'Bangladesch',
      'fr': 'Bangladesh',
      'nl': 'Bangladesh',
      'it': 'Bangladesh',
      'cn': '孟加拉国',
      'ee': 'Bangladesh',
      'jp': 'バングラデシュ',
      'he': 'בנגלדש',
      'tr': 'Bangladeş',
      'ar': 'بنغلاديش',
    },
  ),
  Country(
    code: 'bb',
    name: 'Barbados',
    dialCode: '+1246',
    iso3: 'BRB',
    currency: 'BBD',
    currencyName: 'Barbadian Dollar',
    emoji: '🇧🇧',
    timezones: ['UTC-04:00'],
    region: 'Americas',
    translations: {
      'en': 'Barbados',
      'ru': 'Барбадос',
      'pl': 'Barbados',
      'ua': 'Барбадос',
      'cz': 'Barbados',
      'by': 'Барбадас',
      'pt': 'Barbados',
      'es': 'Barbados',
      'ro': 'Barbados',
      'bg': 'Барбадос',
      'de': 'Barbados',
      'fr': 'Barbade',
      'nl': 'Barbados',
      'it': 'Barbados',
      'cn': '巴巴多斯',
      'ee': 'Barbados',
      'jp': 'バルバドス',
      'he': 'ברבדוס',
      'tr': 'Barbados',
      'ar': 'باربادوس',
    },
  ),
  Country(
    code: 'by',
    name: 'Belarus',
    dialCode: '+375',
    iso3: 'BLR',
    currency: 'BYN',
    currencyName: 'Belarusian Ruble',
    emoji: '🇧🇾',
    timezones: ['UTC+03:00'],
    region: 'Europe',
    translations: {
      'en': 'Belarus',
      'ru': 'Беларусь',
      'pl': 'Białoruś',
      'ua': 'Білорусь',
      'cz': 'Bělorusko',
      'by': 'Беларусь',
      'pt': 'Bielorrússia',
      'es': 'Bielorrusia',
      'ro': 'Belarus',
      'bg': 'Беларус',
      'de': 'Weißrussland',
      'fr': 'Biélorussie',
      'nl': 'Wit-Rusland',
      'it': 'Bielorussia',
      'cn': '白俄罗斯',
      'ee': 'Valgevene',
      'jp': 'ベラルーシ',
      'he': 'בלארוס',
      'tr': 'Belarus',
      'ar': 'بيلاروس',
    },
  ),
  Country(
    code: 'be',
    name: 'Belgium',
    dialCode: '+32',
    iso3: 'BEL',
    currency: 'EUR',
    currencyName: 'Euro',
    emoji: '🇧🇪',
    timezones: ['UTC+01:00'],
    region: 'Europe',
    translations: {
      'en': 'Belgium',
      'ru': 'Бельгия',
      'pl': 'Belgia',
      'ua': 'Бельгія',
      'cz': 'Belgie',
      'by': 'Бельгія',
      'pt': 'Bélgica',
      'es': 'Bélgica',
      'ro': 'Belgia',
      'bg': 'Белгия',
      'de': 'Belgien',
      'fr': 'Belgique',
      'nl': 'België',
      'it': 'Belgio',
      'cn': '比利时',
      'ee': 'Belgia',
      'jp': 'ベルギー',
      'he': 'בלגיה',
      'tr': 'Belçika',
      'ar': 'بلجيكا',
    },
  ),
  Country(
    code: 'bz',
    name: 'Belize',
    dialCode: '+501',
    iso3: 'BLZ',
    currency: 'BZD',
    currencyName: 'Belize Dollar',
    emoji: '🇧🇿',
    timezones: ['UTC-06:00'],
    region: 'Americas',
    translations: {
      'en': 'Belize',
      'ru': 'Белиз',
      'pl': 'Belize',
      'ua': 'Беліз',
      'cz': 'Belize',
      'by': 'Беліз',
      'pt': 'Belize',
      'es': 'Belice',
      'ro': 'Belize',
      'bg': 'Белиз',
      'de': 'Belize',
      'fr': 'Belize',
      'nl': 'Belize',
      'it': 'Belize',
      'cn': '伯利兹',
      'ee': 'Belize',
      'jp': 'ベリーズ',
      'he': 'בליז',
      'tr': 'Belize',
      'ar': 'بليز',
    },
  ),
  Country(
    code: 'bj',
    name: 'Benin',
    dialCode: '+229',
    iso3: 'BEN',
    currency: 'XOF',
    currencyName: 'West African CFA Franc',
    emoji: '🇧🇯',
    timezones: ['UTC+01:00'],
    region: 'Africa',
    translations: {
      'en': 'Benin',
      'ru': 'Бенин',
      'pl': 'Benin',
      'ua': 'Бенін',
      'cz': 'Benin',
      'by': 'Бенін',
      'pt': 'Benim',
      'es': 'Benín',
      'ro': 'Benin',
      'bg': 'Бенин',
      'de': 'Benin',
      'fr': 'Bénin',
      'nl': 'Benin',
      'it': 'Benin',
      'cn': '贝宁',
      'ee': 'Benin',
      'jp': 'ベナン',
      'he': 'בנין',
      'tr': 'Benin',
      'ar': 'بنين',
    },
  ),
  Country(
    code: 'bm',
    name: 'Bermuda',
    dialCode: '+1441',
    iso3: 'BMU',
    currency: 'BMD',
    currencyName: 'Bermudian Dollar',
    emoji: '🇧🇲',
    timezones: ['UTC-04:00'],
    region: 'Americas',
    translations: {
      'en': 'Bermuda',
      'ru': 'Бермудские Острова',
      'pl': 'Bermudy',
      'ua': 'Бермудські Острови',
      'cz': 'Bermudy',
      'by': 'Бермудскія астравы',
      'pt': 'Bermudas',
      'es': 'Bermudas',
      'ro': 'Bermuda',
      'bg': 'Бермудски острови',
      'de': 'Bermuda',
      'fr': 'Bermudes',
      'nl': 'Bermuda',
      'it': 'Bermuda',
      'cn': '百慕大',
      'ee': 'Bermuda',
      'jp': 'バミューダ',
      'he': 'ברמודה',
      'tr': 'Bermuda',
      'ar': 'برمودا',
    },
  ),
  Country(
    code: 'bt',
    name: 'Bhutan',
    dialCode: '+975',
    iso3: 'BTN',
    currency: 'BTN',
    currencyName: 'Bhutanese Ngultrum',
    emoji: '🇧🇹',
    timezones: ['UTC+06:00'],
    region: 'Asia',
    translations: {
      'en': 'Bhutan',
      'ru': 'Бутан',
      'pl': 'Bhutan',
      'ua': 'Бутан',
      'cz': 'Bhútán',
      'by': 'Бутан',
      'pt': 'Butão',
      'es': 'Bután',
      'ro': 'Bhutan',
      'bg': 'Бутан',
      'de': 'Bhutan',
      'fr': 'Bhoutan',
      'nl': 'Bhutan',
      'it': 'Bhutan',
      'cn': '不丹',
      'ee': 'Bhutan',
      'jp': 'ブータン',
      'he': 'בהוטן',
      'tr': 'Bhutan',
      'ar': 'بوتان',
    },
  ),
  Country(
    code: 'bo',
    name: 'Bolivia',
    dialCode: '+591',
    iso3: 'BOL',
    currency: 'BOB',
    currencyName: 'Bolivian Boliviano',
    emoji: '🇧🇴',
    timezones: ['UTC-04:00'],
    region: 'Americas',
    translations: {
      'en': 'Bolivia',
      'ru': 'Боливия',
      'pl': 'Boliwia',
      'ua': 'Болівія',
      'cz': 'Bolívie',
      'by': 'Балівія',
      'pt': 'Bolívia',
      'es': 'Bolivia',
      'ro': 'Bolivia',
      'bg': 'Боливия',
      'de': 'Bolivien',
      'fr': 'Bolivie',
      'nl': 'Bolivia',
      'it': 'Bolivia',
      'cn': '玻利维亚',
      'ee': 'Boliivia',
      'jp': 'ボリビア',
      'he': 'בוליביה',
      'tr': 'Bolivya',
      'ar': 'بوليفيا',
    },
  ),
  Country(
    code: 'ba',
    name: 'Bosnia and Herzegovina',
    dialCode: '+387',
    iso3: 'BIH',
    currency: 'BAM',
    currencyName: 'Bosnia-Herzegovina Convertible Mark',
    emoji: '🇧🇦',
    timezones: ['UTC+01:00'],
    region: 'Europe',
    translations: {
      'en': 'Bosnia and Herzegovina',
      'ru': 'Босния и Герцеговина',
      'pl': 'Bośnia i Hercegowina',
      'ua': 'Боснія і Герцеговина',
      'cz': 'Bosna a Hercegovina',
      'by': 'Боснія і Герцагавіна',
      'pt': 'Bósnia e Herzegovina',
      'es': 'Bosnia y Herzegovina',
      'ro': 'Bosnia și Herțegovina',
      'bg': 'Босна и Херцеговина',
      'de': 'Bosnien und Herzegowina',
      'fr': 'Bosnie-Herzégovine',
      'nl': 'Bosnië en Herzegovina',
      'it': 'Bosnia ed Erzegovina',
      'cn': '波斯尼亚和黑塞哥维那',
      'ee': 'Bosnia ja Hertsegoviina',
      'jp': 'ボスニア・ヘルツェゴビナ',
      'he': 'בוסניה והרצגובינה',
      'tr': 'Bosna-Hersek',
      'ar': 'البوسنة والهرسك',
    },
  ),
  Country(
    code: 'bw',
    name: 'Botswana',
    dialCode: '+267',
    iso3: 'BWA',
    currency: 'BWP',
    currencyName: 'Botswana Pula',
    emoji: '🇧🇼',
    timezones: ['UTC+02:00'],
    region: 'Africa',
    translations: {
      'en': 'Botswana',
      'ru': 'Ботсвана',
      'pl': 'Botswana',
      'ua': 'Ботсвана',
      'cz': 'Botswana',
      'by': 'Батсвана',
      'pt': 'Botsuana',
      'es': 'Botsuana',
      'ro': 'Botswana',
      'bg': 'Ботсвана',
      'de': 'Botswana',
      'fr': 'Botswana',
      'nl': 'Botswana',
      'it': 'Botswana',
      'cn': '博茨瓦纳',
      'ee': 'Botswana',
      'jp': 'ボツワナ',
      'he': 'בוטסואנה',
      'tr': 'Botsvana',
      'ar': 'بوتسوانا',
    },
  ),
  Country(
    code: 'br',
    name: 'Brazil',
    dialCode: '+55',
    iso3: 'BRA',
    currency: 'BRL',
    currencyName: 'Brazilian Real',
    emoji: '🇧🇷',
    timezones: ['UTC-05:00', 'UTC-04:00', 'UTC-03:00', 'UTC-02:00'],
    region: 'Americas',
    translations: {
      'en': 'Brazil',
      'ru': 'Бразилия',
      'pl': 'Brazylia',
      'ua': 'Бразилія',
      'cz': 'Brazílie',
      'by': 'Бразілія',
      'pt': 'Brasil',
      'es': 'Brasil',
      'ro': 'Brazilia',
      'bg': 'Бразилия',
      'de': 'Brasilien',
      'fr': 'Brésil',
      'nl': 'Brazilië',
      'it': 'Brasile',
      'cn': '巴西',
      'ee': 'Brasiilia',
      'jp': 'ブラジル',
      'he': 'ברזיל',
      'tr': 'Brezilya',
      'ar': 'البرازيل',
    },
  ),
  Country(
    code: 'bn',
    name: 'Brunei Darussalam',
    dialCode: '+673',
    iso3: 'BRN',
    currency: 'BND',
    currencyName: 'Brunei Dollar',
    emoji: '🇧🇳',
    timezones: ['UTC+08:00'],
    region: 'Asia',
    translations: {
      'en': 'Brunei Darussalam',
      'ru': 'Бруней-Даруссалам',
      'pl': 'Brunei',
      'ua': 'Бруней',
      'cz': 'Brunej',
      'by': 'Бруней',
      'pt': 'Brunei',
      'es': 'Brunéi',
      'ro': 'Brunei',
      'bg': 'Бруней',
      'de': 'Brunei',
      'fr': 'Brunei',
      'nl': 'Brunei',
      'it': 'Brunei',
      'cn': '文莱',
      'ee': 'Brunei',
      'jp': 'ブルネイ',
      'he': 'ברוניי',
      'tr': 'Brunei',
      'ar': 'بروناي',
    },
  ),
  Country(
    code: 'bg',
    name: 'Bulgaria',
    dialCode: '+359',
    iso3: 'BGR',
    currency: 'BGN',
    currencyName: 'Bulgarian Lev',
    emoji: '🇧🇬',
    timezones: ['UTC+02:00'],
    region: 'Europe',
    translations: {
      'en': 'Bulgaria',
      'ru': 'Болгария',
      'pl': 'Bułgaria',
      'ua': 'Болгарія',
      'cz': 'Bulharsko',
      'by': 'Балгарыя',
      'pt': 'Bulgária',
      'es': 'Bulgaria',
      'ro': 'Bulgaria',
      'bg': 'България',
      'de': 'Bulgarien',
      'fr': 'Bulgarie',
      'nl': 'Bulgarije',
      'it': 'Bulgaria',
      'cn': '保加利亚',
      'ee': 'Bulgaaria',
      'jp': 'ブルガリア',
      'he': 'בולגריה',
      'tr': 'Bulgaristan',
      'ar': 'بلغاريا',
    },
  ),
  Country(
    code: 'bf',
    name: 'Burkina Faso',
    dialCode: '+226',
    iso3: 'BFA',
    currency: 'XOF',
    currencyName: 'West African CFA Franc',
    emoji: '🇧🇫',
    timezones: ['UTC'],
    region: 'Africa',
    translations: {
      'en': 'Burkina Faso',
      'ru': 'Буркина-Фасо',
      'pl': 'Burkina Faso',
      'ua': 'Буркіна-Фасо',
      'cz': 'Burkina Faso',
      'by': 'Буркіна-Фасо',
      'pt': 'Burquina Faso',
      'es': 'Burkina Faso',
      'ro': 'Burkina Faso',
      'bg': 'Буркина Фасо',
      'de': 'Burkina Faso',
      'fr': 'Burkina Faso',
      'nl': 'Burkina Faso',
      'it': 'Burkina Faso',
      'cn': '布基纳法索',
      'ee': 'Burkina Faso',
      'jp': 'ブルキナファソ',
      'he': 'בורקינה פאסו',
      'tr': 'Burkina Faso',
      'ar': 'بوركينا فاسو',
    },
  ),
  Country(
    code: 'bi',
    name: 'Burundi',
    dialCode: '+257',
    iso3: 'BDI',
    currency: 'BIF',
    currencyName: 'Burundian Franc',
    emoji: '🇧🇮',
    timezones: ['UTC+02:00'],
    region: 'Africa',
    translations: {
      'en': 'Burundi',
      'ru': 'Бурунди',
      'pl': 'Burundi',
      'ua': 'Бурунді',
      'cz': 'Burundi',
      'by': 'Бурундзі',
      'pt': 'Burundi',
      'es': 'Burundi',
      'ro': 'Burundi',
      'bg': 'Бурунди',
      'de': 'Burundi',
      'fr': 'Burundi',
      'nl': 'Burundi',
      'it': 'Burundi',
      'cn': '布隆迪',
      'ee': 'Burundi',
      'jp': 'ブルンジ',
      'he': 'בורונדי',
      'tr': 'Burundi',
      'ar': 'بوروندي',
    },
  ),
  Country(
    code: 'cv',
    name: 'Cabo Verde',
    dialCode: '+238',
    iso3: 'CPV',
    currency: 'CVE',
    currencyName: 'Cape Verdean Escudo',
    emoji: '🇨🇻',
    timezones: ['UTC-01:00'],
    region: 'Africa',
    translations: {
      'en': 'Cabo Verde',
      'ru': 'Кабо-Верде',
      'pl': 'Republika Zielonego Przylądka',
      'ua': 'Кабо-Верде',
      'cz': 'Kapverdy',
      'by': 'Каба-Вердэ',
      'pt': 'Cabo Verde',
      'es': 'Cabo Verde',
      'ro': 'Capul Verde',
      'bg': 'Кабо Верде',
      'de': 'Kap Verde',
      'fr': 'Cap-Vert',
      'nl': 'Kaapverdië',
      'it': 'Capo Verde',
      'cn': '佛得角',
      'ee': 'Cabo Verde',
      'jp': 'カーボベルデ',
      'he': 'כף ורדה',
      'tr': 'Cape Verde',
      'ar': 'الرأس الأخضر',
    },
  ),
  Country(
    code: 'kh',
    name: 'Cambodia',
    dialCode: '+855',
    iso3: 'KHM',
    currency: 'KHR',
    currencyName: 'Cambodian Riel',
    emoji: '🇰🇭',
    timezones: ['UTC+07:00'],
    region: 'Asia',
    translations: {
      'en': 'Cambodia',
      'ru': 'Камбоджа',
      'pl': 'Kambodża',
      'ua': 'Камбоджа',
      'cz': 'Kambodža',
      'by': 'Камбоджа',
      'pt': 'Camboja',
      'es': 'Camboya',
      'ro': 'Cambodgia',
      'bg': 'Камбоджа',
      'de': 'Kambodscha',
      'fr': 'Cambodge',
      'nl': 'Cambodja',
      'it': 'Cambogia',
      'cn': '柬埔寨',
      'ee': 'Kambodža',
      'jp': 'カンボジア',
      'he': 'קמבודיה',
      'tr': 'Kamboçya',
      'ar': 'كمبوديا',
    },
  ),
  Country(
    code: 'cm',
    name: 'Cameroon',
    dialCode: '+237',
    iso3: 'CMR',
    currency: 'XAF',
    currencyName: 'Central African CFA Franc',
    emoji: '🇨🇲',
    timezones: ['UTC+01:00'],
    region: 'Africa',
    translations: {
      'en': 'Cameroon',
      'ru': 'Камерун',
      'pl': 'Kamerun',
      'ua': 'Камерун',
      'cz': 'Kamerun',
      'by': 'Камерун',
      'pt': 'Camarões',
      'es': 'Camerún',
      'ro': 'Camerun',
      'bg': 'Камерун',
      'de': 'Kamerun',
      'fr': 'Cameroun',
      'nl': 'Kameroen',
      'it': 'Camerun',
      'cn': '喀麦隆',
      'ee': 'Kamerun',
      'jp': 'カメルーン',
      'he': 'קמרון',
      'tr': 'Kamerun',
      'ar': 'الكاميرون',
    },
  ),
  Country(
    code: 'ca',
    name: 'Canada',
    dialCode: '+1',
    iso3: 'CAN',
    currency: 'CAD',
    currencyName: 'Canadian Dollar',
    emoji: '🇨🇦',
    timezones: ['UTC-08:00', 'UTC-07:00', 'UTC-06:00', 'UTC-05:00', 'UTC-04:00', 'UTC-03:30'],
    region: 'Americas',
    translations: {
      'en': 'Canada',
      'ru': 'Канада',
      'pl': 'Kanada',
      'ua': 'Канада',
      'cz': 'Kanada',
      'by': 'Канада',
      'pt': 'Canadá',
      'es': 'Canadá',
      'ro': 'Canada',
      'bg': 'Канада',
      'de': 'Kanada',
      'fr': 'Canada',
      'nl': 'Canada',
      'it': 'Canada',
      'cn': '加拿大',
      'ee': 'Kanada',
      'jp': 'カナダ',
      'he': 'קנדה',
      'tr': 'Kanada',
      'ar': 'كندا',
    },
  ),
  Country(
    code: 'cf',
    name: 'Central African Republic',
    dialCode: '+236',
    iso3: 'CAF',
    currency: 'XAF',
    currencyName: 'Central African CFA Franc',
    emoji: '🇨🇫',
    timezones: ['UTC+01:00'],
    region: 'Africa',
    translations: {
      'en': 'Central African Republic',
      'ru': 'Центрально-Африканская Республика',
      'pl': 'Republika Środkowoafrykańska',
      'ua': 'Центральноафриканська Республіка',
      'cz': 'Středoafrická republika',
      'by': 'Цэнтральна-Афрыканская Рэспубліка',
      'pt': 'República Centro-Africana',
      'es': 'República Centroafricana',
      'ro': 'Republica Centrafricană',
      'bg': 'Централноафриканска република',
      'de': 'Zentralafrikanische Republik',
      'fr': 'République centrafricaine',
      'nl': 'Centraal-Afrikaanse Republiek',
      'it': 'Repubblica Centrafricana',
      'cn': '中非共和国',
      'ee': 'Kesk-Aafrika Vabariik',
      'jp': '中央アフリカ共和国',
      'he': 'הרפובליקה המרכז אפריקאית',
      'tr': 'Orta Afrika Cumhuriyeti',
      'ar': 'جمهورية أفريقيا الوسطى',
    },
  ),
  Country(
    code: 'td',
    name: 'Chad',
    dialCode: '+235',
    iso3: 'TCD',
    currency: 'XAF',
    currencyName: 'Central African CFA Franc',
    emoji: '🇹🇩',
    timezones: ['UTC+01:00'],
    region: 'Africa',
    translations: {
      'en': 'Chad',
      'ru': 'Чад',
      'pl': 'Czad',
      'ua': 'Чад',
      'cz': 'Čad',
      'by': 'Чад',
      'pt': 'Chade',
      'es': 'Chad',
      'ro': 'Ciad',
      'bg': 'Чад',
      'de': 'Tschad',
      'fr': 'Tchad',
      'nl': 'Tsjaad',
      'it': 'Ciad',
      'cn': '乍得',
      'ee': 'Tšaad',
      'jp': 'チャド',
      'he': 'צ׳אד',
      'tr': 'Çad',
      'ar': 'تشاد',
    },
  ),
  Country(
    code: 'cl',
    name: 'Chile',
    dialCode: '+56',
    iso3: 'CHL',
    currency: 'CLP',
    currencyName: 'Chilean Peso',
    emoji: '🇨🇱',
    timezones: ['UTC-06:00', 'UTC-04:00'],
    region: 'Americas',
    translations: {
      'en': 'Chile',
      'ru': 'Чили',
      'pl': 'Chile',
      'ua': 'Чилі',
      'cz': 'Chile',
      'by': 'Чылі',
      'pt': 'Chile',
      'es': 'Chile',
      'ro': 'Chile',
      'bg': 'Чили',
      'de': 'Chile',
      'fr': 'Chili',
      'nl': 'Chili',
      'it': 'Cile',
      'cn': '智利',
      'ee': 'Tšiili',
      'jp': 'チリ',
      'he': 'צ׳ילה',
      'tr': 'Şili',
      'ar': 'تشيلي',
    },
  ),
  Country(
    code: 'cn',
    name: 'China',
    dialCode: '+86',
    iso3: 'CHN',
    currency: 'CNY',
    currencyName: 'Chinese Yuan',
    emoji: '🇨🇳',
    timezones: ['UTC+08:00'],
    region: 'Asia',
    translations: {
      'en': 'China',
      'ru': 'Китай',
      'pl': 'Chiny',
      'ua': 'Китай',
      'cz': 'Čína',
      'by': 'Кітай',
      'pt': 'China',
      'es': 'China',
      'ro': 'China',
      'bg': 'Китай',
      'de': 'China',
      'fr': 'Chine',
      'nl': 'China',
      'it': 'Cina',
      'cn': '中国',
      'ee': 'Hiina',
      'jp': '中国',
      'he': 'סין',
      'tr': 'Çin',
      'ar': 'الصين',
    },
  ),
  Country(
    code: 'co',
    name: 'Colombia',
    dialCode: '+57',
    iso3: 'COL',
    currency: 'COP',
    currencyName: 'Colombian Peso',
    emoji: '🇨🇴',
    timezones: ['UTC-05:00'],
    region: 'Americas',
    translations: {
      'en': 'Colombia',
      'ru': 'Колумбия',
      'pl': 'Kolumbia',
      'ua': 'Колумбія',
      'cz': 'Kolumbie',
      'by': 'Калумбія',
      'pt': 'Colômbia',
      'es': 'Colombia',
      'ro': 'Columbia',
      'bg': 'Колумбия',
      'de': 'Kolumbien',
      'fr': 'Colombie',
      'nl': 'Colombia',
      'it': 'Colombia',
      'cn': '哥伦比亚',
      'ee': 'Colombia',
      'jp': 'コロンビア',
      'he': 'קולומביה',
      'tr': 'Kolombiya',
      'ar': 'كولومبيا',
    },
  ),
  Country(
    code: 'km',
    name: 'Comoros',
    dialCode: '+269',
    iso3: 'COM',
    currency: 'KMF',
    currencyName: 'Comorian Franc',
    emoji: '🇰🇲',
    timezones: ['UTC+03:00'],
    region: 'Africa',
    translations: {
      'en': 'Comoros',
      'ru': 'Коморы',
      'pl': 'Komory',
      'ua': 'Коморські Острови',
      'cz': 'Komory',
      'by': 'Каморскія астравы',
      'pt': 'Comores',
      'es': 'Comoras',
      'ro': 'Comore',
      'bg': 'Коморски острови',
      'de': 'Komoren',
      'fr': 'Comores',
      'nl': 'Comoren',
      'it': 'Comore',
      'cn': '科摩罗',
      'ee': 'Komoorid',
      'jp': 'コモロ',
      'he': 'קומורו',
      'tr': 'Komorlar',
      'ar': 'جزر القمر',
    },
  ),
  Country(
    code: 'cg',
    name: 'Congo',
    dialCode: '+242',
    iso3: 'COG',
    currency: 'XAF',
    currencyName: 'Central African CFA Franc',
    emoji: '🇨🇬',
    timezones: ['UTC+01:00'],
    region: 'Africa',
    translations: {
      'en': 'Congo',
      'ru': 'Конго',
      'pl': 'Kongo',
      'ua': 'Конго',
      'cz': 'Kongo',
      'by': 'Конга',
      'pt': 'Congo',
      'es': 'Congo',
      'ro': 'Congo',
      'bg': 'Конго',
      'de': 'Kongo',
      'fr': 'Congo',
      'nl': 'Congo',
      'it': 'Congo',
      'cn': '刚果',
      'ee': 'Kongo',
      'jp': 'コンゴ',
      'he': 'קונגו',
      'tr': 'Kongo',
      'ar': 'الكونغو',
    },
  ),
  Country(
    code: 'cd',
    name: 'Congo, Democratic Republic of the',
    dialCode: '+243',
    iso3: 'COD',
    currency: 'CDF',
    currencyName: 'Congolese Franc',
    emoji: '🇨🇩',
    timezones: ['UTC+01:00', 'UTC+02:00'],
    region: 'Africa',
    translations: {
      'en': 'Democratic Republic of the Congo',
      'ru': 'Демократическая Республика Конго',
      'pl': 'Demokratyczna Republika Konga',
      'ua': 'Демократична Республіка Конго',
      'cz': 'Demokratická republika Kongo',
      'by': 'Дэмакратычная Рэспубліка Конга',
      'pt': 'República Democrática do Congo',
      'es': 'República Democrática del Congo',
      'ro': 'Republica Democrată Congo',
      'bg': 'Демократична република Конго',
      'de': 'Demokratische Republik Kongo',
      'fr': 'République démocratique du Congo',
      'nl': 'Congo-Kinshasa',
      'it': 'Repubblica Democratica del Congo',
      'cn': '刚果民主共和国',
      'ee': 'Kongo Demokraatlik Vabariik',
      'jp': 'コンゴ民主共和国',
      'he': 'הרפובליקה הדמוקרטית של קונגו',
      'tr': 'Kongo Demokratik Cumhuriyeti',
      'ar': 'جمهورية الكونغو الديمقراطية',
    },
  ),
  Country(
    code: 'cr',
    name: 'Costa Rica',
    dialCode: '+506',
    iso3: 'CRI',
    currency: 'CRC',
    currencyName: 'Costa Rican Colón',
    emoji: '🇨🇷',
    timezones: ['UTC-06:00'],
    region: 'Americas',
    translations: {
      'en': 'Costa Rica',
      'ru': 'Коста-Рика',
      'pl': 'Kostaryka',
      'ua': 'Коста-Рика',
      'cz': 'Kostarika',
      'by': 'Коста-Рыка',
      'pt': 'Costa Rica',
      'es': 'Costa Rica',
      'ro': 'Costa Rica',
      'bg': 'Коста Рика',
      'de': 'Costa Rica',
      'fr': 'Costa Rica',
      'nl': 'Costa Rica',
      'it': 'Costa Rica',
      'cn': '哥斯达黎加',
      'ee': 'Costa Rica',
      'jp': 'コスタリカ',
      'he': 'קוסטה ריקה',
      'tr': 'Kosta Rika',
      'ar': 'كوستاريكا',
    },
  ),
  Country(
    code: 'ci',
    name: "Côte d'Ivoire",
    dialCode: '+225',
    iso3: 'CIV',
    currency: 'XOF',
    currencyName: 'West African CFA Franc',
    emoji: '🇨🇮',
    timezones: ['UTC'],
    region: 'Africa',
    translations: {
      'en': "Côte d'Ivoire",
      'ru': 'Кот-д’Ивуар',
      'pl': 'Wybrzeże Kości Słoniowej',
      'ua': "Кот-д'Івуар",
      'cz': 'Pobřeží slonoviny',
      'by': "Кот-д'Івуар",
      'pt': 'Costa do Marfim',
      'es': 'Costa de Marfil',
      'ro': 'Coasta de Fildeș',
      'bg': "Кот д'Ивоар",
      'de': 'Elfenbeinküste',
      'fr': "Côte d'Ivoire",
      'nl': 'Ivoorkust',
      'it': "Costa d'Avorio",
      'cn': '科特迪瓦',
      'ee': 'Elevandiluurannik',
      'jp': 'コートジボワール',
      'he': "חוף השנהב",
      'tr': "Fildişi Sahili",
      'ar': "ساحل العاج",
    },
  ),
  Country(
    code: 'hr',
    name: 'Croatia',
    dialCode: '+385',
    iso3: 'HRV',
    currency: 'HRK',
    currencyName: 'Croatian Kuna',
    emoji: '🇭🇷',
    timezones: ['UTC+01:00'],
    region: 'Europe',
    translations: {
      'en': 'Croatia',
      'ru': 'Хорватия',
      'pl': 'Chorwacja',
      'ua': 'Хорватія',
      'cz': 'Chorvatsko',
      'by': 'Харватыя',
      'pt': 'Croácia',
      'es': 'Croacia',
      'ro': 'Croația',
      'bg': 'Хърватия',
      'de': 'Kroatien',
      'fr': 'Croatie',
      'nl': 'Kroatië',
      'it': 'Croazia',
      'cn': '克罗地亚',
      'ee': 'Horvaatia',
      'jp': 'クロアチア',
      'he': 'קרואטיה',
      'tr': 'Hırvatistan',
      'ar': 'كرواتيا',
    },
  ),
  Country(
    code: 'cu',
    name: 'Cuba',
    dialCode: '+53',
    iso3: 'CUB',
    currency: 'CUP',
    currencyName: 'Cuban Peso',
    emoji: '🇨🇺',
    timezones: ['UTC-05:00'],
    region: 'Americas',
    translations: {
      'en': 'Cuba',
      'ru': 'Куба',
      'pl': 'Kuba',
      'ua': 'Куба',
      'cz': 'Kuba',
      'by': 'Куба',
      'pt': 'Cuba',
      'es': 'Cuba',
      'ro': 'Cuba',
      'bg': 'Куба',
      'de': 'Kuba',
      'fr': 'Cuba',
      'nl': 'Cuba',
      'it': 'Cuba',
      'cn': '古巴',
      'ee': 'Kuuba',
      'jp': 'キューバ',
      'he': 'קובה',
      'tr': 'Küba',
      'ar': 'كوبا',
    },
  ),
  Country(
    code: 'cy',
    name: 'Cyprus',
    dialCode: '+357',
    iso3: 'CYP',
    currency: 'EUR',
    currencyName: 'Euro',
    emoji: '🇨🇾',
    timezones: ['UTC+02:00'],
    region: 'Europe',
    translations: {
      'en': 'Cyprus',
      'ru': 'Кипр',
      'pl': 'Cypr',
      'ua': 'Кіпр',
      'cz': 'Kypr',
      'by': 'Кіпр',
      'pt': 'Chipre',
      'es': 'Chipre',
      'ro': 'Cipru',
      'bg': 'Кипър',
      'de': 'Zypern',
      'fr': 'Chypre',
      'nl': 'Cyprus',
      'it': 'Cipro',
      'cn': '塞浦路斯',
      'ee': 'Küpros',
      'jp': 'キプロス',
      'he': 'קפריסין',
      'tr': 'Kıbrıs',
      'ar': 'قبرص',
    },
  ),
  Country(
    code: 'cz',
    name: 'Czech Republic',
    dialCode: '+420',
    iso3: 'CZE',
    currency: 'CZK',
    currencyName: 'Czech Koruna',
    emoji: '🇨🇿',
    timezones: ['UTC+01:00'],
    region: 'Europe',
    translations: {
      'en': 'Czech Republic',
      'ru': 'Чехия',
      'pl': 'Czechy',
      'ua': 'Чехія',
      'cz': 'Česko',
      'by': 'Чэхія',
      'pt': 'República Checa',
      'es': 'República Checa',
      'ro': 'Cehia',
      'bg': 'Чехия',
      'de': 'Tschechien',
      'fr': 'République tchèque',
      'nl': 'Tsjechië',
      'it': 'Repubblica Ceca',
      'cn': '捷克',
      'ee': 'Tšehhi',
      'jp': 'チェコ',
      'he': 'צ׳כיה',
      'tr': 'Çek Cumhuriyeti',
      'ar': 'التشيك',
    },
  ),
  Country(
    code: 'dk',
    name: 'Denmark',
    dialCode: '+45',
    iso3: 'DNK',
    currency: 'DKK',
    currencyName: 'Danish Krone',
    emoji: '🇩🇰',
    timezones: ['UTC+01:00'],
    region: 'Europe',
    translations: {
      'en': 'Denmark',
      'ru': 'Дания',
      'pl': 'Dania',
      'ua': 'Данія',
      'cz': 'Dánsko',
      'by': 'Данія',
      'pt': 'Dinamarca',
      'es': 'Dinamarca',
      'ro': 'Danemarca',
      'bg': 'Дания',
      'de': 'Dänemark',
      'fr': 'Danemark',
      'nl': 'Denemarken',
      'it': 'Danimarca',
      'cn': '丹麦',
      'ee': 'Taani',
      'jp': 'デンマーク',
      'he': 'דנמרק',
      'tr': 'Danimarka',
      'ar': 'الدنمارك',
    },
  ),
  Country(
    code: 'dj',
    name: 'Djibouti',
    dialCode: '+253',
    iso3: 'DJI',
    currency: 'DJF',
    currencyName: 'Djiboutian Franc',
    emoji: '🇩🇯',
    timezones: ['UTC+03:00'],
    region: 'Africa',
    translations: {
      'en': 'Djibouti',
      'ru': 'Джибути',
      'pl': 'Dżibuti',
      'ua': 'Джибуті',
      'cz': 'Džibutsko',
      'by': 'Джыбуці',
      'pt': 'Djibouti',
      'es': 'Yibuti',
      'ro': 'Djibouti',
      'bg': 'Джибути',
      'de': 'Dschibuti',
      'fr': 'Djibouti',
      'nl': 'Djibouti',
      'it': 'Gibuti',
      'cn': '吉布提',
      'ee': 'Djibouti',
      'jp': 'ジブチ',
      'he': 'ג׳יבוטי',
      'tr': 'Cibuti',
      'ar': 'جيبوتي',
    },
  ),
  Country(
    code: 'dm',
    name: 'Dominica',
    dialCode: '+1767',
    iso3: 'DMA',
    currency: 'XCD',
    currencyName: 'East Caribbean Dollar',
    emoji: '🇩🇲',
    timezones: ['UTC-04:00'],
    region: 'Americas',
    translations: {
      'en': 'Dominica',
      'ru': 'Доминика',
      'pl': 'Dominika',
      'ua': 'Домініка',
      'cz': 'Dominika',
      'by': 'Дамініка',
      'pt': 'Dominica',
      'es': 'Dominica',
      'ro': 'Dominica',
      'bg': 'Доминика',
      'de': 'Dominica',
      'fr': 'Dominique',
      'nl': 'Dominica',
      'it': 'Dominica',
      'cn': '多米尼克',
      'ee': 'Dominica',
      'jp': 'ドミニカ国',
      'he': 'דומיניקה',
      'tr': 'Dominika',
      'ar': 'دومينيكا',
    },
  ),
  Country(
    code: 'do',
    name: 'Dominican Republic',
    dialCode: '+1849',
    iso3: 'DOM',
    currency: 'DOP',
    currencyName: 'Dominican Peso',
    emoji: '🇩🇴',
    timezones: ['UTC-04:00'],
    region: 'Americas',
    translations: {
      'en': 'Dominican Republic',
      'ru': 'Доминиканская Республика',
      'pl': 'Dominikana',
      'ua': 'Домініканська Республіка',
      'cz': 'Dominikánská republika',
      'by': 'Дамініканская Рэспубліка',
      'pt': 'República Dominicana',
      'es': 'República Dominicana',
      'ro': 'Republica Dominicană',
      'bg': 'Доминиканска република',
      'de': 'Dominikanische Republik',
      'fr': 'République dominicaine',
      'nl': 'Dominicaanse Republiek',
      'it': 'Repubblica Dominicana',
      'cn': '多米尼加共和国',
      'ee': 'Dominikaani Vabariik',
      'jp': 'ドミニカ共和国',
      'he': 'הרפובליקה הדומיניקנית',
      'tr': 'Dominik Cumhuriyeti',
      'ar': 'جمهورية الدومينيكان',
    },
  ),
   Country(
    code: 'ec',
    name: 'Ecuador',
    dialCode: '+593',
    iso3: 'ECU',
    currency: 'USD',
    currencyName: 'US Dollar',
    emoji: '🇪🇨',
    timezones: ['UTC-06:00', 'UTC-05:00'],
    region: 'Americas',
    translations: {
      'en': 'Ecuador',
      'ru': 'Эквадор',
      'pl': 'Ekwador',
      'ua': 'Еквадор',
      'cz': 'Ekvádor',
      'by': 'Эквадор',
      'pt': 'Equador',
      'es': 'Ecuador',
      'ro': 'Ecuador',
      'bg': 'Еквадор',
      'de': 'Ecuador',
      'fr': 'Équateur',
      'nl': 'Ecuador',
      'it': 'Ecuador',
      'cn': '厄瓜多尔',
      'ee': 'Ecuador',
      'jp': 'エクアドル',
      'he': 'אקוודור',
      'tr': 'Ekvador',
      'ar': 'الإكوادور',
    },
  ),
  Country(
    code: 'eg',
    name: 'Egypt',
    dialCode: '+20',
    iso3: 'EGY',
    currency: 'EGP',
    currencyName: 'Egyptian Pound',
    emoji: '🇪🇬',
    timezones: ['UTC+02:00'],
    region: 'Africa',
    translations: {
      'en': 'Egypt',
      'ru': 'Египет',
      'pl': 'Egipt',
      'ua': 'Єгипет',
      'cz': 'Egypt',
      'by': 'Егіпет',
      'pt': 'Egito',
      'es': 'Egipto',
      'ro': 'Egipt',
      'bg': 'Египет',
      'de': 'Ägypten',
      'fr': 'Égypte',
      'nl': 'Egypte',
      'it': 'Egitto',
      'cn': '埃及',
      'ee': 'Egiptus',
      'jp': 'エジプト',
      'he': 'מצרים',
      'tr': 'Mısır',
      'ar': 'مصر',
    },
  ),
  Country(
    code: 'sv',
    name: 'El Salvador',
    dialCode: '+503',
    iso3: 'SLV',
    currency: 'USD',
    currencyName: 'US Dollar',
    emoji: '🇸🇻',
    timezones: ['UTC-06:00'],
    region: 'Americas',
    translations: {
      'en': 'El Salvador',
      'ru': 'Сальвадор',
      'pl': 'Salwador',
      'ua': 'Сальвадор',
      'cz': 'Salvador',
      'by': 'Сальвадор',
      'pt': 'El Salvador',
      'es': 'El Salvador',
      'ro': 'El Salvador',
      'bg': 'Ел Салвадор',
      'de': 'El Salvador',
      'fr': 'Salvador',
      'nl': 'El Salvador',
      'it': 'El Salvador',
      'cn': '萨尔瓦多',
      'ee': 'El Salvador',
      'jp': 'エルサルバドル',
      'he': 'אל סלבדור',
      'tr': 'El Salvador',
      'ar': 'السلفادور',
    },
  ),
  Country(
    code: 'gq',
    name: 'Equatorial Guinea',
    dialCode: '+240',
    iso3: 'GNQ',
    currency: 'XAF',
    currencyName: 'Central African CFA Franc',
    emoji: '🇬🇶',
    timezones: ['UTC+01:00'],
    region: 'Africa',
    translations: {
      'en': 'Equatorial Guinea',
      'ru': 'Экваториальная Гвинея',
      'pl': 'Gwinea Równikowa',
      'ua': 'Екваторіальна Гвінея',
      'cz': 'Rovníková Guinea',
      'by': 'Экватарыяльная Гвінея',
      'pt': 'Guiné Equatorial',
      'es': 'Guinea Ecuatorial',
      'ro': 'Guineea Ecuatorială',
      'bg': 'Екваториална Гвинея',
      'de': 'Äquatorialguinea',
      'fr': 'Guinée équatoriale',
      'nl': 'Equatoriaal-Guinea',
      'it': 'Guinea Equatoriale',
      'cn': '赤道几内亚',
      'ee': 'Ekvatoriaal-Guinea',
      'jp': '赤道ギニア',
      'he': 'גינאה המשוונית',
      'tr': 'Ekvator Ginesi',
      'ar': 'غينيا الاستوائية',
    },
  ),
  Country(
    code: 'er',
    name: 'Eritrea',
    dialCode: '+291',
    iso3: 'ERI',
    currency: 'ERN',
    currencyName: 'Eritrean Nakfa',
    emoji: '🇪🇷',
    timezones: ['UTC+03:00'],
    region: 'Africa',
    translations: {
      'en': 'Eritrea',
      'ru': 'Эритрея',
      'pl': 'Erytrea',
      'ua': 'Еритрея',
      'cz': 'Eritrea',
      'by': 'Эрытрэя',
      'pt': 'Eritreia',
      'es': 'Eritrea',
      'ro': 'Eritreea',
      'bg': 'Еритрея',
      'de': 'Eritrea',
      'fr': 'Érythrée',
      'nl': 'Eritrea',
      'it': 'Eritrea',
      'cn': '厄立特里亚',
      'ee': 'Eritrea',
      'jp': 'エリトリア',
      'he': 'אריתריאה',
      'tr': 'Eritre',
      'ar': 'إريتريا',
    },
  ),
  Country(
    code: 'ee',
    name: 'Estonia',
    dialCode: '+372',
    iso3: 'EST',
    currency: 'EUR',
    currencyName: 'Euro',
    emoji: '🇪🇪',
    timezones: ['UTC+02:00'],
    region: 'Europe',
    translations: {
      'en': 'Estonia',
      'ru': 'Эстония',
      'pl': 'Estonia',
      'ua': 'Естонія',
      'cz': 'Estonsko',
      'by': 'Эстонія',
      'pt': 'Estónia',
      'es': 'Estonia',
      'ro': 'Estonia',
      'bg': 'Естония',
      'de': 'Estland',
      'fr': 'Estonie',
      'nl': 'Estland',
      'it': 'Estonia',
      'cn': '爱沙尼亚',
      'ee': 'Eesti',
      'jp': 'エストニア',
      'he': 'אסטוניה',
      'tr': 'Estonya',
      'ar': 'إستونيا',
    },
  ),
  Country(
    code: 'sz',
    name: 'Eswatini',
    dialCode: '+268',
    iso3: 'SWZ',
    currency: 'SZL',
    currencyName: 'Swazi Lilangeni',
    emoji: '🇸🇿',
    timezones: ['UTC+02:00'],
    region: 'Africa',
    translations: {
      'en': 'Eswatini',
      'ru': 'Эсватини',
      'pl': 'Eswatini',
      'ua': 'Есватіні',
      'cz': 'Eswatini',
      'by': 'Эсваціні',
      'pt': 'Essuatíni',
      'es': 'Esuatini',
      'ro': 'Eswatini',
      'bg': 'Есватини',
      'de': 'Eswatini',
      'fr': 'Eswatini',
      'nl': 'Eswatini',
      'it': 'Eswatini',
      'cn': '斯威士兰',
      'ee': 'Eswatini',
      'jp': 'エスワティニ',
      'he': 'אסוואטיני',
      'tr': 'Esvatini',
      'ar': 'إسواتيني',
    },
  ),
  Country(
    code: 'et',
    name: 'Ethiopia',
    dialCode: '+251',
    iso3: 'ETH',
    currency: 'ETB',
    currencyName: 'Ethiopian Birr',
    emoji: '🇪🇹',
    timezones: ['UTC+03:00'],
    region: 'Africa',
    translations: {
      'en': 'Ethiopia',
      'ru': 'Эфиопия',
      'pl': 'Etiopia',
      'ua': 'Ефіопія',
      'cz': 'Etiopie',
      'by': 'Эфіопія',
      'pt': 'Etiópia',
      'es': 'Etiopía',
      'ro': 'Etiopia',
      'bg': 'Етиопия',
      'de': 'Äthiopien',
      'fr': 'Éthiopie',
      'nl': 'Ethiopië',
      'it': 'Etiopia',
      'cn': '埃塞俄比亚',
      'ee': 'Etioopia',
      'jp': 'エチオピア',
      'he': 'אתיופיה',
      'tr': 'Etiyopya',
      'ar': 'إثيوبيا',
    },
  ),
  Country(
    code: 'fj',
    name: 'Fiji',
    dialCode: '+679',
    iso3: 'FJI',
    currency: 'FJD',
    currencyName: 'Fijian Dollar',
    emoji: '🇫🇯',
    timezones: ['UTC+12:00'],
    region: 'Oceania',
    translations: {
      'en': 'Fiji',
      'ru': 'Фиджи',
      'pl': 'Fidżi',
      'ua': 'Фіджі',
      'cz': 'Fidži',
      'by': 'Фіджы',
      'pt': 'Fiji',
      'es': 'Fiyi',
      'ro': 'Fiji',
      'bg': 'Фиджи',
      'de': 'Fidschi',
      'fr': 'Fidji',
      'nl': 'Fiji',
      'it': 'Figi',
      'cn': '斐济',
      'ee': 'Fidži',
      'jp': 'フィジー',
      'he': 'פיג׳י',
      'tr': 'Fiji',
      'ar': 'فيجي',
    },
  ),
  Country(
    code: 'fi',
    name: 'Finland',
    dialCode: '+358',
    iso3: 'FIN',
    currency: 'EUR',
    currencyName: 'Euro',
    emoji: '🇫🇮',
    timezones: ['UTC+02:00'],
    region: 'Europe',
    translations: {
      'en': 'Finland',
      'ru': 'Финляндия',
      'pl': 'Finlandia',
      'ua': 'Фінляндія',
      'cz': 'Finsko',
      'by': 'Фінляндыя',
      'pt': 'Finlândia',
      'es': 'Finlandia',
      'ro': 'Finlanda',
      'bg': 'Финландия',
      'de': 'Finnland',
      'fr': 'Finlande',
      'nl': 'Finland',
      'it': 'Finlandia',
      'cn': '芬兰',
      'ee': 'Soome',
      'jp': 'フィンランド',
      'he': 'פינלנד',
      'tr': 'Finlandiya',
      'ar': 'فنلندا',
    },
  ),
  Country(
    code: 'ga',
    name: 'Gabon',
    dialCode: '+241',
    iso3: 'GAB',
    currency: 'XAF',
    currencyName: 'Central African CFA Franc',
    emoji: '🇬🇦',
    timezones: ['UTC+01:00'],
    region: 'Africa',
    translations: {
      'en': 'Gabon',
      'ru': 'Габон',
      'pl': 'Gabon',
      'ua': 'Габон',
      'cz': 'Gabon',
      'by': 'Габон',
      'pt': 'Gabão',
      'es': 'Gabón',
      'ro': 'Gabon',
      'bg': 'Габон',
      'de': 'Gabun',
      'fr': 'Gabon',
      'nl': 'Gabon',
      'it': 'Gabon',
      'cn': '加蓬',
      'ee': 'Gabon',
      'jp': 'ガボン',
      'he': 'גבון',
      'tr': 'Gabon',
      'ar': 'الغابون',
    },
  ),
  Country(
    code: 'gm',
    name: 'Gambia',
    dialCode: '+220',
    iso3: 'GMB',
    currency: 'GMD',
    currencyName: 'Gambian Dalasi',
    emoji: '🇬🇲',
    timezones: ['UTC'],
    region: 'Africa',
    translations: {
      'en': 'Gambia',
      'ru': 'Гамбия',
      'pl': 'Gambia',
      'ua': 'Гамбія',
      'cz': 'Gambie',
      'by': 'Гамбія',
      'pt': 'Gâmbia',
      'es': 'Gambia',
      'ro': 'Gambia',
      'bg': 'Гамбия',
      'de': 'Gambia',
      'fr': 'Gambie',
      'nl': 'Gambia',
      'it': 'Gambia',
      'cn': '冈比亚',
      'ee': 'Gambia',
      'jp': 'ガンビア',
      'he': 'גמביה',
      'tr': 'Gambiya',
      'ar': 'غامبيا',
    },
  ),
  Country(
    code: 'ge',
    name: 'Georgia',
    dialCode: '+995',
    iso3: 'GEO',
    currency: 'GEL',
    currencyName: 'Georgian Lari',
    emoji: '🇬🇪',
    timezones: ['UTC+04:00'],
    region: 'Asia',
    translations: {
      'en': 'Georgia',
      'ru': 'Грузия',
      'pl': 'Gruzja',
      'ua': 'Грузія',
      'cz': 'Gruzie',
      'by': 'Грузія',
      'pt': 'Geórgia',
      'es': 'Georgia',
      'ro': 'Georgia',
      'bg': 'Грузия',
      'de': 'Georgien',
      'fr': 'Géorgie',
      'nl': 'Georgië',
      'it': 'Georgia',
      'cn': '格鲁吉亚',
      'ee': 'Gruusia',
      'jp': 'ジョージア',
      'he': 'גאורגיה',
      'tr': 'Gürcistan',
      'ar': 'جورجيا',
    },
  ),
  Country(
    code: 'gh',
    name: 'Ghana',
    dialCode: '+233',
    iso3: 'GHA',
    currency: 'GHS',
    currencyName: 'Ghanaian Cedi',
    emoji: '🇬🇭',
    timezones: ['UTC'],
    region: 'Africa',
    translations: {
      'en': 'Ghana',
      'ru': 'Гана',
      'pl': 'Ghana',
      'ua': 'Гана',
      'cz': 'Ghana',
      'by': 'Гана',
      'pt': 'Gana',
      'es': 'Ghana',
      'ro': 'Ghana',
      'bg': 'Гана',
      'de': 'Ghana',
      'fr': 'Ghana',
      'nl': 'Ghana',
      'it': 'Ghana',
      'cn': '加纳',
      'ee': 'Ghana',
      'jp': 'ガーナ',
      'he': 'גאנה',
      'tr': 'Gana',
      'ar': 'غانا',
    },
  ),
  Country(
    code: 'gr',
    name: 'Greece',
    dialCode: '+30',
    iso3: 'GRC',
    currency: 'EUR',
    currencyName: 'Euro',
    emoji: '🇬🇷',
    timezones: ['UTC+02:00'],
    region: 'Europe',
    translations: {
      'en': 'Greece',
      'ru': 'Греция',
      'pl': 'Grecja',
      'ua': 'Греція',
      'cz': 'Řecko',
      'by': 'Грэцыя',
      'pt': 'Grécia',
      'es': 'Grecia',
      'ro': 'Grecia',
      'bg': 'Гърция',
      'de': 'Griechenland',
      'fr': 'Grèce',
      'nl': 'Griekenland',
      'it': 'Grecia',
      'cn': '希腊',
      'ee': 'Kreeka',
      'jp': 'ギリシャ',
      'he': 'יוון',
      'tr': 'Yunanistan',
      'ar': 'اليونان',
    },
  ),
  Country(
    code: 'gd',
    name: 'Grenada',
    dialCode: '+1473',
    iso3: 'GRD',
    currency: 'XCD',
    currencyName: 'East Caribbean Dollar',
    emoji: '🇬🇩',
    timezones: ['UTC-04:00'],
    region: 'Americas',
    translations: {
      'en': 'Grenada',
      'ru': 'Гренада',
      'pl': 'Grenada',
      'ua': 'Гренада',
      'cz': 'Grenada',
      'by': 'Грэнада',
      'pt': 'Granada',
      'es': 'Granada',
      'ro': 'Grenada',
      'bg': 'Гренада',
      'de': 'Grenada',
      'fr': 'Grenade',
      'nl': 'Grenada',
      'it': 'Grenada',
      'cn': '格林纳达',
      'ee': 'Grenada',
      'jp': 'グレナダ',
      'he': 'גרנדה',
      'tr': 'Grenada',
      'ar': 'غرينادا',
    },
  ),
  Country(
    code: 'gt',
    name: 'Guatemala',
    dialCode: '+502',
    iso3: 'GTM',
    currency: 'GTQ',
    currencyName: 'Guatemalan Quetzal',
    emoji: '🇬🇹',
    timezones: ['UTC-06:00'],
    region: 'Americas',
    translations: {
      'en': 'Guatemala',
      'ru': 'Гватемала',
      'pl': 'Gwatemala',
      'ua': 'Гватемала',
      'cz': 'Guatemala',
      'by': 'Гватэмала',
      'pt': 'Guatemala',
      'es': 'Guatemala',
      'ro': 'Guatemala',
      'bg': 'Гватемала',
      'de': 'Guatemala',
      'fr': 'Guatemala',
      'nl': 'Guatemala',
      'it': 'Guatemala',
      'cn': '危地马拉',
      'ee': 'Guatemala',
      'jp': 'グアテマラ',
      'he': 'גואטמלה',
      'tr': 'Guatemala',
      'ar': 'غواتيمالا',
    },
  ),
  Country(
    code: 'gn',
    name: 'Guinea',
    dialCode: '+224',
    iso3: 'GIN',
    currency: 'GNF',
    currencyName: 'Guinean Franc',
    emoji: '🇬🇳',
    timezones: ['UTC'],
    region: 'Africa',
    translations: {
      'en': 'Guinea',
      'ru': 'Гвинея',
      'pl': 'Gwinea',
      'ua': 'Гвінея',
      'cz': 'Guinea',
      'by': 'Гвінея',
      'pt': 'Guiné',
      'es': 'Guinea',
      'ro': 'Guineea',
      'bg': 'Гвинея',
      'de': 'Guinea',
      'fr': 'Guinée',
      'nl': 'Guinee',
      'it': 'Guinea',
      'cn': '几内亚',
      'ee': 'Guinea',
      'jp': 'ギニア',
      'he': 'גינאה',
      'tr': 'Gine',
      'ar': 'غينيا',
    },
  ),
  Country(
    code: 'gw',
    name: 'Guinea-Bissau',
    dialCode: '+245',
    iso3: 'GNB',
    currency: 'XOF',
    currencyName: 'West African CFA Franc',
    emoji: '🇬🇼',
    timezones: ['UTC'],
    region: 'Africa',
    translations: {
      'en': 'Guinea-Bissau',
      'ru': 'Гвинея-Бисау',
      'pl': 'Gwinea Bissau',
      'ua': 'Гвінея-Бісау',
      'cz': 'Guinea-Bissau',
      'by': 'Гвінея-Бісау',
      'pt': 'Guiné-Bissau',
      'es': 'Guinea-Bisáu',
      'ro': 'Guineea-Bissau',
      'bg': 'Гвинея-Бисау',
      'de': 'Guinea-Bissau',
      'fr': 'Guinée-Bissau',
      'nl': 'Guinee-Bissau',
      'it': 'Guinea-Bissau',
      'cn': '几内亚比绍',
      'ee': 'Guinea-Bissau',
      'jp': 'ギニアビサウ',
      'he': 'גינאה ביסאו',
      'tr': 'Gine-Bissau',
      'ar': 'غينيا بيساو',
    },
  ),
  Country(
    code: 'gy',
    name: 'Guyana',
    dialCode: '+592',
    iso3: 'GUY',
    currency: 'GYD',
    currencyName: 'Guyanese Dollar',
    emoji: '🇬🇾',
    timezones: ['UTC-04:00'],
    region: 'Americas',
    translations: {
      'en': 'Guyana',
      'ru': 'Гайана',
      'pl': 'Gujana',
      'ua': 'Гайана',
      'cz': 'Guyana',
      'by': 'Гаяна',
      'pt': 'Guiana',
      'es': 'Guyana',
      'ro': 'Guyana',
      'bg': 'Гайана',
      'de': 'Guyana',
      'fr': 'Guyana',
      'nl': 'Guyana',
      'it': 'Guyana',
      'cn': '圭亚那',
      'ee': 'Guyana',
      'jp': 'ガイアナ',
      'he': 'גיאנה',
      'tr': 'Guyana',
      'ar': 'غيانا',
    },
  ),
  Country(
    code: 'ht',
    name: 'Haiti',
    dialCode: '+509',
    iso3: 'HTI',
    currency: 'HTG',
    currencyName: 'Haitian Gourde',
    emoji: '🇭🇹',
    timezones: ['UTC-05:00'],
    region: 'Americas',
    translations: {
      'en': 'Haiti',
      'ru': 'Гаити',
      'pl': 'Haiti',
      'ua': 'Гаїті',
      'cz': 'Haiti',
      'by': 'Гаіці',
      'pt': 'Haiti',
      'es': 'Haití',
      'ro': 'Haiti',
      'bg': 'Хаити',
      'de': 'Haiti',
      'fr': 'Haïti',
      'nl': 'Haïti',
      'it': 'Haiti',
      'cn': '海地',
      'ee': 'Haiti',
      'jp': 'ハイチ',
      'he': 'האיטי',
      'tr': 'Haiti',
      'ar': 'هايتي',
    },
  ),
  Country(
    code: 'hn',
    name: 'Honduras',
    dialCode: '+504',
    iso3: 'HND',
    currency: 'HNL',
    currencyName: 'Honduran Lempira',
    emoji: '🇭🇳',
    timezones: ['UTC-06:00'],
    region: 'Americas',
    translations: {
      'en': 'Honduras',
      'ru': 'Гондурас',
      'pl': 'Honduras',
      'ua': 'Гондурас',
      'cz': 'Honduras',
      'by': 'Гандурас',
      'pt': 'Honduras',
      'es': 'Honduras',
      'ro': 'Honduras',
      'bg': 'Хондурас',
      'de': 'Honduras',
      'fr': 'Honduras',
      'nl': 'Honduras',
      'it': 'Honduras',
      'cn': '洪都拉斯',
      'ee': 'Honduras',
      'jp': 'ホンジュラス',
      'he': 'הונדורס',
      'tr': 'Honduras',
      'ar': 'هندوراس',
    },
  ),
  Country(
    code: 'hu',
    name: 'Hungary',
    dialCode: '+36',
    iso3: 'HUN',
    currency: 'HUF',
    currencyName: 'Hungarian Forint',
    emoji: '🇭🇺',
    timezones: ['UTC+01:00'],
    region: 'Europe',
    translations: {
      'en': 'Hungary',
      'ru': 'Венгрия',
      'pl': 'Węgry',
      'ua': 'Угорщина',
      'cz': 'Maďarsko',
      'by': 'Венгрыя',
      'pt': 'Hungria',
      'es': 'Hungría',
      'ro': 'Ungaria',
      'bg': 'Унгария',
      'de': 'Ungarn',
      'fr': 'Hongrie',
      'nl': 'Hongarije',
      'it': 'Ungheria',
      'cn': '匈牙利',
      'ee': 'Ungari',
      'jp': 'ハンガリー',
      'he': 'הונגריה',
      'tr': 'Macaristan',
      'ar': 'المجر',
    },
  ),
  Country(
    code: 'is',
    name: 'Iceland',
    dialCode: '+354',
    iso3: 'ISL',
    currency: 'ISK',
    currencyName: 'Icelandic Króna',
    emoji: '🇮🇸',
    timezones: ['UTC'],
    region: 'Europe',
    translations: {
      'en': 'Iceland',
      'ru': 'Исландия',
      'pl': 'Islandia',
      'ua': 'Ісландія',
      'cz': 'Island',
      'by': 'Ісландыя',
      'pt': 'Islândia',
      'es': 'Islandia',
      'ro': 'Islanda',
      'bg': 'Исландия',
      'de': 'Island',
      'fr': 'Islande',
      'nl': 'IJsland',
      'it': 'Islanda',
      'cn': '冰岛',
      'ee': 'Island',
      'jp': 'アイスランド',
      'he': 'איסלנד',
      'tr': 'İzlanda',
      'ar': 'آيسلندا',
    },
  ),
  Country(
    code: 'in',
    name: 'India',
    dialCode: '+91',
    iso3: 'IND',
    currency: 'INR',
    currencyName: 'Indian Rupee',
    emoji: '🇮🇳',
    timezones: ['UTC+05:30'],
    region: 'Asia',
    translations: {
      'en': 'India',
      'ru': 'Индия',
      'pl': 'Indie',
      'ua': 'Індія',
      'cz': 'Indie',
      'by': 'Індыя',
      'pt': 'Índia',
      'es': 'India',
      'ro': 'India',
      'bg': 'Индия',
      'de': 'Indien',
      'fr': 'Inde',
      'nl': 'India',
      'it': 'India',
      'cn': '印度',
      'ee': 'India',
      'jp': 'インド',
      'he': 'הודו',
      'tr': 'Hindistan',
      'ar': 'الهند',
    },
  ),
  Country(
    code: 'id',
    name: 'Indonesia',
    dialCode: '+62',
    iso3: 'IDN',
    currency: 'IDR',
    currencyName: 'Indonesian Rupiah',
    emoji: '🇮🇩',
    timezones: ['UTC+07:00', 'UTC+08:00', 'UTC+09:00'],
    region: 'Asia',
    translations: {
      'en': 'Indonesia',
      'ru': 'Индонезия',
      'pl': 'Indonezja',
      'ua': 'Індонезія',
      'cz': 'Indonésie',
      'by': 'Інданезія',
      'pt': 'Indonésia',
      'es': 'Indonesia',
      'ro': 'Indonezia',
      'bg': 'Индонезия',
      'de': 'Indonesien',
      'fr': 'Indonésie',
      'nl': 'Indonesië',
      'it': 'Indonesia',
      'cn': '印度尼西亚',
      'ee': 'Indoneesia',
      'jp': 'インドネシア',
      'he': 'אינדונזיה',
      'tr': 'Endonezya',
      'ar': 'إندونيسيا',
    },
  ),
  Country(
    code: 'ir',
    name: 'Iran',
    dialCode: '+98',
    iso3: 'IRN',
    currency: 'IRR',
    currencyName: 'Iranian Rial',
    emoji: '🇮🇷',
    timezones: ['UTC+03:30'],
    region: 'Asia',
    translations: {
      'en': 'Iran',
      'ru': 'Иран',
      'pl': 'Iran',
      'ua': 'Іран',
      'cz': 'Írán',
      'by': 'Іран',
      'pt': 'Irão',
      'es': 'Irán',
      'ro': 'Iran',
      'bg': 'Иран',
      'de': 'Iran',
      'fr': 'Iran',
      'nl': 'Iran',
      'it': 'Iran',
      'cn': '伊朗',
      'ee': 'Iraan',
      'jp': 'イラン',
      'he': 'איראן',
      'tr': 'İran',
      'ar': 'إيران',
    },
  ),
  Country(
    code: 'iq',
    name: 'Iraq',
    dialCode: '+964',
    iso3: 'IRQ',
    currency: 'IQD',
    currencyName: 'Iraqi Dinar',
    emoji: '🇮🇶',
    timezones: ['UTC+03:00'],
    region: 'Asia',
    translations: {
      'en': 'Iraq',
      'ru': 'Ирак',
      'pl': 'Irak',
      'ua': 'Ірак',
      'cz': 'Irák',
      'by': 'Ірак',
      'pt': 'Iraque',
      'es': 'Irak',
      'ro': 'Irak',
      'bg': 'Ирак',
      'de': 'Irak',
      'fr': 'Irak',
      'nl': 'Irak',
      'it': 'Iraq',
      'cn': '伊拉克',
      'ee': 'Iraak',
      'jp': 'イラク',
      'he': 'עיראק',
      'tr': 'Irak',
      'ar': 'العراق',
    },
  ),
  Country(
    code: 'ie',
    name: 'Ireland',
    dialCode: '+353',
    iso3: 'IRL',
    currency: 'EUR',
    currencyName: 'Euro',
    emoji: '🇮🇪',
    timezones: ['UTC'],
    region: 'Europe',
    translations: {
      'en': 'Ireland',
      'ru': 'Ирландия',
      'pl': 'Irlandia',
      'ua': 'Ірландія',
      'cz': 'Irsko',
      'by': 'Ірландыя',
      'pt': 'Irlanda',
      'es': 'Irlanda',
      'ro': 'Irlanda',
      'bg': 'Ирландия',
      'de': 'Irland',
      'fr': 'Irlande',
      'nl': 'Ierland',
      'it': 'Irlanda',
      'cn': '爱尔兰',
      'ee': 'Iirimaa',
      'jp': 'アイルランド',
      'he': 'אירלנד',
      'tr': 'İrlanda',
      'ar': 'أيرلندا',
    },
  ),
  Country(
    code: 'il',
    name: 'Israel',
    dialCode: '+972',
    iso3: 'ISR',
    currency: 'ILS',
    currencyName: 'Israeli New Shekel',
    emoji: '🇮🇱',
    timezones: ['UTC+02:00'],
    region: 'Asia',
    translations: {
      'en': 'Israel',
      'ru': 'Израиль',
      'pl': 'Izrael',
      'ua': 'Ізраїль',
      'cz': 'Izrael',
      'by': 'Ізраіль',
      'pt': 'Israel',
      'es': 'Israel',
      'ro': 'Israel',
      'bg': 'Израел',
      'de': 'Israel',
      'fr': 'Israël',
      'nl': 'Israël',
      'it': 'Israele',
      'cn': '以色列',
      'ee': 'Iisrael',
      'jp': 'イスラエル',
      'he': 'ישראל',
      'tr': 'İsrail',
      'ar': 'إسرائيل',
    },
  ),
  Country(
    code: 'it',
    name: 'Italy',
    dialCode: '+39',
    iso3: 'ITA',
    currency: 'EUR',
    currencyName: 'Euro',
    emoji: '🇮🇹',
    timezones: ['UTC+01:00'],
    region: 'Europe',
    translations: {
      'en': 'Italy',
      'ru': 'Италия',
      'pl': 'Włochy',
      'ua': 'Італія',
      'cz': 'Itálie',
      'by': 'Італія',
      'pt': 'Itália',
      'es': 'Italia',
      'ro': 'Italia',
      'bg': 'Италия',
      'de': 'Italien',
      'fr': 'Italie',
      'nl': 'Italië',
      'it': 'Italia',
      'cn': '意大利',
      'ee': 'Itaalia',
      'jp': 'イタリア',
      'he': 'איטליה',
      'tr': 'İtalya',
      'ar': 'إيطاليا',
    },
  ),
  Country(
    code: 'jm',
    name: 'Jamaica',
    dialCode: '+1876',
    iso3: 'JAM',
    currency: 'JMD',
    currencyName: 'Jamaican Dollar',
    emoji: '🇯🇲',
    timezones: ['UTC-05:00'],
    region: 'Americas',
    translations: {
      'en': 'Jamaica',
      'ru': 'Ямайка',
      'pl': 'Jamajka',
      'ua': 'Ямайка',
      'cz': 'Jamajka',
      'by': 'Ямайка',
      'pt': 'Jamaica',
      'es': 'Jamaica',
      'ro': 'Jamaica',
      'bg': 'Ямайка',
      'de': 'Jamaika',
      'fr': 'Jamaïque',
      'nl': 'Jamaica',
      'it': 'Giamaica',
      'cn': '牙买加',
      'ee': 'Jamaica',
      'jp': 'ジャマイカ',
      'he': 'ג׳מייקה',
      'tr': 'Jamaika',
      'ar': 'جامايكا',
    },
  ),
  Country(
    code: 'jp',
    name: 'Japan',
    dialCode: '+81',
    iso3: 'JPN',
    currency: 'JPY',
    currencyName: 'Japanese Yen',
    emoji: '🇯🇵',
    timezones: ['UTC+09:00'],
    region: 'Asia',
    translations: {
      'en': 'Japan',
      'ru': 'Япония',
      'pl': 'Japonia',
      'ua': 'Японія',
      'cz': 'Japonsko',
      'by': 'Японія',
      'pt': 'Japão',
      'es': 'Japón',
      'ro': 'Japonia',
      'bg': 'Япония',
      'de': 'Japan',
      'fr': 'Japon',
      'nl': 'Japan',
      'it': 'Giappone',
      'cn': '日本',
      'ee': 'Jaapan',
      'jp': '日本',
      'he': 'יפן',
      'tr': 'Japonya',
      'ar': 'اليابان',
    },
  ),
  Country(
    code: 'jo',
    name: 'Jordan',
    dialCode: '+962',
    iso3: 'JOR',
    currency: 'JOD',
    currencyName: 'Jordanian Dinar',
    emoji: '🇯🇴',
    timezones: ['UTC+02:00'],
    region: 'Asia',
    translations: {
      'en': 'Jordan',
      'ru': 'Иордания',
      'pl': 'Jordania',
      'ua': 'Йорданія',
      'cz': 'Jordánsko',
      'by': 'Іарданія',
      'pt': 'Jordânia',
      'es': 'Jordania',
      'ro': 'Iordania',
      'bg': 'Йордания',
      'de': 'Jordanien',
      'fr': 'Jordanie',
      'nl': 'Jordanië',
      'it': 'Giordania',
      'cn': '约旦',
      'ee': 'Jordaania',
      'jp': 'ヨルダン',
      'he': 'ירדן',
      'tr': 'Ürdün',
      'ar': 'الأردن',
    },
  ),
  Country(
    code: 'kz',
    name: 'Kazakhstan',
    dialCode: '+7',
    iso3: 'KAZ',
    currency: 'KZT',
    currencyName: 'Kazakhstani Tenge',
    emoji: '🇰🇿',
    timezones: ['UTC+05:00', 'UTC+06:00'],
    region: 'Asia',
    translations: {
      'en': 'Kazakhstan',
      'ru': 'Казахстан',
      'pl': 'Kazachstan',
      'ua': 'Казахстан',
      'cz': 'Kazachstán',
      'by': 'Казахстан',
      'pt': 'Cazaquistão',
      'es': 'Kazajistán',
      'ro': 'Kazahstan',
      'bg': 'Казахстан',
      'de': 'Kasachstan',
      'fr': 'Kazakhstan',
      'nl': 'Kazachstan',
      'it': 'Kazakistan',
      'cn': '哈萨克斯坦',
      'ee': 'Kasahstan',
      'jp': 'カザフスタン',
      'he': 'קזחסטן',
      'tr': 'Kazakistan',
      'ar': 'كازاخستان',
    },
  ),
  Country(
    code: 'ke',
    name: 'Kenya',
    dialCode: '+254',
    iso3: 'KEN',
    currency: 'KES',
    currencyName: 'Kenyan Shilling',
    emoji: '🇰🇪',
    timezones: ['UTC+03:00'],
    region: 'Africa',
    translations: {
      'en': 'Kenya',
      'ru': 'Кения',
      'pl': 'Kenia',
      'ua': 'Кенія',
      'cz': 'Keňa',
      'by': 'Кенія',
      'pt': 'Quénia',
      'es': 'Kenia',
      'ro': 'Kenya',
      'bg': 'Кения',
      'de': 'Kenia',
      'fr': 'Kenya',
      'nl': 'Kenia',
      'it': 'Kenya',
      'cn': '肯尼亚',
      'ee': 'Keenia',
      'jp': 'ケニア',
      'he': 'קניה',
      'tr': 'Kenya',
      'ar': 'كينيا',
    },
  ),
  Country(
    code: 'ki',
    name: 'Kiribati',
    dialCode: '+686',
    iso3: 'KIR',
    currency: 'AUD',
    currencyName: 'Australian Dollar',
    emoji: '🇰🇮',
    timezones: ['UTC+12:00', 'UTC+13:00', 'UTC+14:00'],
    region: 'Oceania',
    translations: {
      'en': 'Kiribati',
      'ru': 'Кирибати',
      'pl': 'Kiribati',
      'ua': 'Кірибаті',
      'cz': 'Kiribati',
      'by': 'Кірыбаці',
      'pt': 'Quiribáti',
      'es': 'Kiribati',
      'ro': 'Kiribati',
      'bg': 'Кирибати',
      'de': 'Kiribati',
      'fr': 'Kiribati',
      'nl': 'Kiribati',
      'it': 'Kiribati',
      'cn': '基里巴斯',
      'ee': 'Kiribati',
      'jp': 'キリバス',
      'he': 'קיריבטי',
      'tr': 'Kiribati',
      'ar': 'كيريباتي',
    },
  ),
  Country(
    code: 'kw',
    name: 'Kuwait',
    dialCode: '+965',
    iso3: 'KWT',
    currency: 'KWD',
    currencyName: 'Kuwaiti Dinar',
    emoji: '🇰🇼',
    timezones: ['UTC+03:00'],
    region: 'Asia',
    translations: {
      'en': 'Kuwait',
      'ru': 'Кувейт',
      'pl': 'Kuwejt',
      'ua': 'Кувейт',
      'cz': 'Kuvajt',
      'by': 'Кувейт',
      'pt': 'Kuwait',
      'es': 'Kuwait',
      'ro': 'Kuweit',
      'bg': 'Кувейт',
      'de': 'Kuwait',
      'fr': 'Koweït',
      'nl': 'Koeweit',
      'it': 'Kuwait',
      'cn': '科威特',
      'ee': 'Kuveit',
      'jp': 'クウェート',
      'he': 'כווית',
      'tr': 'Kuveyt',
      'ar': 'الكويت',
    },
  ),
  Country(
    code: 'kg',
    name: 'Kyrgyzstan',
    dialCode: '+996',
    iso3: 'KGZ',
    currency: 'KGS',
    currencyName: 'Kyrgyzstani Som',
    emoji: '🇰🇬',
    timezones: ['UTC+06:00'],
    region: 'Asia',
    translations: {
      'en': 'Kyrgyzstan',
      'ru': 'Киргизия',
      'pl': 'Kirgistan',
      'ua': 'Киргизстан',
      'cz': 'Kyrgyzstán',
      'by': 'Кыргызстан',
      'pt': 'Quirguistão',
      'es': 'Kirguistán',
      'ro': 'Kârgâzstan',
      'bg': 'Киргизстан',
      'de': 'Kirgisistan',
      'fr': 'Kirghizistan',
      'nl': 'Kirgizië',
      'it': 'Kirghizistan',
      'cn': '吉尔吉斯斯坦',
      'ee': 'Kõrgõzstan',
      'jp': 'キルギス',
      'he': 'קירגיזסטן',
      'tr': 'Kırgızistan',
      'ar': 'قيرغيزستان',
    },
  ),
  Country(
    code: 'la',
    name: 'Laos',
    dialCode: '+856',
    iso3: 'LAO',
    currency: 'LAK',
    currencyName: 'Lao Kip',
    emoji: '🇱🇦',
    timezones: ['UTC+07:00'],
    region: 'Asia',
    translations: {
      'en': 'Laos',
      'ru': 'Лаос',
      'pl': 'Laos',
      'ua': 'Лаос',
      'cz': 'Laos',
      'by': 'Лаос',
      'pt': 'Laos',
      'es': 'Laos',
      'ro': 'Laos',
      'bg': 'Лаос',
      'de': 'Laos',
      'fr': 'Laos',
      'nl': 'Laos',
      'it': 'Laos',
      'cn': '老挝',
      'ee': 'Laos',
      'jp': 'ラオス',
      'he': 'לאוס',
      'tr': 'Laos',
      'ar': 'لاوس',
    },
  ),
  Country(
    code: 'lv',
    name: 'Latvia',
    dialCode: '+371',
    iso3: 'LVA',
    currency: 'EUR',
    currencyName: 'Euro',
    emoji: '🇱🇻',
    timezones: ['UTC+02:00'],
    region: 'Europe',
    translations: {
      'en': 'Latvia',
      'ru': 'Латвия',
      'pl': 'Łotwa',
      'ua': 'Латвія',
      'cz': 'Lotyšsko',
      'by': 'Латвія',
      'pt': 'Letónia',
      'es': 'Letonia',
      'ro': 'Letonia',
      'bg': 'Латвия',
      'de': 'Lettland',
      'fr': 'Lettonie',
      'nl': 'Letland',
      'it': 'Lettonia',
      'cn': '拉脱维亚',
      'ee': 'Läti',
      'jp': 'ラトビア',
      'he': 'לטביה',
      'tr': 'Letonya',
      'ar': 'لاتفيا',
    },
  ),
  Country(
    code: 'lb',
    name: 'Lebanon',
    dialCode: '+961',
    iso3: 'LBN',
    currency: 'LBP',
    currencyName: 'Lebanese Pound',
    emoji: '🇱🇧',
    timezones: ['UTC+02:00'],
    region: 'Asia',
    translations: {
      'en': 'Lebanon',
      'ru': 'Ливан',
      'pl': 'Liban',
      'ua': 'Ліван',
      'cz': 'Libanon',
      'by': 'Ліван',
      'pt': 'Líbano',
      'es': 'Líbano',
      'ro': 'Liban',
      'bg': 'Ливан',
      'de': 'Libanon',
      'fr': 'Liban',
      'nl': 'Libanon',
      'it': 'Libano',
      'cn': '黎巴嫩',
      'ee': 'Liibanon',
      'jp': 'レバノン',
      'he': 'לבנון',
      'tr': 'Lübnan',
      'ar': 'لبنان',
    },
  ),
  Country(
    code: 'ls',
    name: 'Lesotho',
    dialCode: '+266',
    iso3: 'LSO',
    currency: 'LSL',
    currencyName: 'Lesotho Loti',
    emoji: '🇱🇸',
    timezones: ['UTC+02:00'],
    region: 'Africa',
    translations: {
      'en': 'Lesotho',
      'ru': 'Лесото',
      'pl': 'Lesotho',
      'ua': 'Лесото',
      'cz': 'Lesotho',
      'by': 'Лесота',
      'pt': 'Lesoto',
      'es': 'Lesoto',
      'ro': 'Lesotho',
      'bg': 'Лесото',
      'de': 'Lesotho',
      'fr': 'Lesotho',
      'nl': 'Lesotho',
      'it': 'Lesotho',
      'cn': '莱索托',
      'ee': 'Lesotho',
      'jp': 'レソト',
      'he': 'לסוטו',
      'tr': 'Lesotho',
      'ar': 'ليسوتو',
    },
  ),
  Country(
    code: 'lr',
    name: 'Liberia',
    dialCode: '+231',
    iso3: 'LBR',
    currency: 'LRD',
    currencyName: 'Liberian Dollar',
    emoji: '🇱🇷',
    timezones: ['UTC'],
    region: 'Africa',
    translations: {
      'en': 'Liberia',
      'ru': 'Либерия',
      'pl': 'Liberia',
      'ua': 'Ліберія',
      'cz': 'Libérie',
      'by': 'Ліберыя',
      'pt': 'Libéria',
      'es': 'Liberia',
      'ro': 'Liberia',
      'bg': 'Либерия',
      'de': 'Liberia',
      'fr': 'Libéria',
      'nl': 'Liberia',
      'it': 'Liberia',
      'cn': '利比里亚',
      'ee': 'Libeeria',
      'jp': 'リベリア',
      'he': 'ליבריה',
      'tr': 'Liberya',
      'ar': 'ليبيريا',
    },
  ),
  Country(
    code: 'ly',
    name: 'Libya',
    dialCode: '+218',
    iso3: 'LBY',
    currency: 'LYD',
    currencyName: 'Libyan Dinar',
    emoji: '🇱🇾',
    timezones: ['UTC+02:00'],
    region: 'Africa',
    translations: {
      'en': 'Libya',
      'ru': 'Ливия',
      'pl': 'Libia',
      'ua': 'Лівія',
      'cz': 'Libye',
      'by': 'Лівія',
      'pt': 'Líbia',
      'es': 'Libia',
      'ro': 'Libia',
      'bg': 'Либия',
      'de': 'Libyen',
      'fr': 'Libye',
      'nl': 'Libië',
      'it': 'Libia',
      'cn': '利比亚',
      'ee': 'Liibüa',
      'jp': 'リビア',
      'he': 'לוב',
      'tr': 'Libya',
      'ar': 'ليبيا',
    },
  ),
  Country(
    code: 'li',
    name: 'Liechtenstein',
    dialCode: '+423',
    iso3: 'LIE',
    currency: 'CHF',
    currencyName: 'Swiss Franc',
    emoji: '🇱🇮',
    timezones: ['UTC+01:00'],
    region: 'Europe',
    translations: {
      'en': 'Liechtenstein',
      'ru': 'Лихтенштейн',
      'pl': 'Liechtenstein',
      'ua': 'Ліхтенштейн',
      'cz': 'Lichtenštejnsko',
      'by': 'Ліхтэнштэйн',
      'pt': 'Liechtenstein',
      'es': 'Liechtenstein',
      'ro': 'Liechtenstein',
      'bg': 'Лихтенщайн',
      'de': 'Liechtenstein',
      'fr': 'Liechtenstein',
      'nl': 'Liechtenstein',
      'it': 'Liechtenstein',
      'cn': '列支敦士登',
      'ee': 'Liechtenstein',
      'jp': 'リヒテンシュタイン',
      'he': 'ליכטנשטיין',
      'tr': 'Lihtenştayn',
      'ar': 'ليختنشتاين',
    },
  ),
  Country(
    code: 'lt',
    name: 'Lithuania',
    dialCode: '+370',
    iso3: 'LTU',
    currency: 'EUR',
    currencyName: 'Euro',
    emoji: '🇱🇹',
    timezones: ['UTC+02:00'],
    region: 'Europe',
    translations: {
      'en': 'Lithuania',
      'ru': 'Литва',
      'pl': 'Litwa',
      'ua': 'Литва',
      'cz': 'Litva',
      'by': 'Літва',
      'pt': 'Lituânia',
      'es': 'Lituania',
      'ro': 'Lituania',
      'bg': 'Литва',
      'de': 'Litauen',
      'fr': 'Lituanie',
      'nl': 'Litouwen',
      'it': 'Lituania',
      'cn': '立陶宛',
      'ee': 'Leedu',
      'jp': 'リトアニア',
      'he': 'ליטא',
      'tr': 'Litvanya',
      'ar': 'ليتوانيا',
    },
  ),
  Country(
    code: 'lu',
    name: 'Luxembourg',
    dialCode: '+352',
    iso3: 'LUX',
    currency: 'EUR',
    currencyName: 'Euro',
    emoji: '🇱🇺',
    timezones: ['UTC+01:00'],
    region: 'Europe',
    translations: {
      'en': 'Luxembourg',
      'ru': 'Люксембург',
      'pl': 'Luksemburg',
      'ua': 'Люксембург',
      'cz': 'Lucembursko',
      'by': 'Люксембург',
      'pt': 'Luxemburgo',
      'es': 'Luxemburgo',
      'ro': 'Luxemburg',
      'bg': 'Люксембург',
      'de': 'Luxemburg',
      'fr': 'Luxembourg',
      'nl': 'Luxemburg',
      'it': 'Lussemburgo',
      'cn': '卢森堡',
      'ee': 'Luksemburg',
      'jp': 'ルクセンブルク',
      'he': 'לוקסמבורג',
      'tr': 'Lüksemburg',
      'ar': 'لوكسمبورغ',
    },
  ),


];

// Le reste de votre code CountryService reste inchangé
class CountryService {
  static final Map<String, Country> _byCode = {};
  static final Map<String, List<Country>> _byCurrency = {};
  static final Map<String, List<Country>> _byRegion = {};
  static final Map<String, List<Country>> _byTimezone = {};

  static void initialize() {
    if (_byCode.isNotEmpty) return;
    
    for (final country in defaultCountries) {
      _byCode[country.code.toLowerCase()] = country;
      _byCurrency.putIfAbsent(country.currency.toUpperCase(), () => []).add(country);
      _byRegion.putIfAbsent(country.region.toLowerCase(), () => []).add(country);
      
      for (final tz in country.timezones) {
        _byTimezone.putIfAbsent(tz.toLowerCase(), () => []).add(country);
      }
    }
  }

  static Country? byCode(String code) => _byCode[code.toLowerCase()];
  static List<Country> byCurrency(String currency) => _byCurrency[currency.toUpperCase()] ?? [];
  static List<Country> byRegion(String region) => _byRegion[region.toLowerCase()] ?? [];
  static List<Country> byTimezone(String timezone) => _byTimezone[timezone.toLowerCase()] ?? [];

  static List<Country> search(String query, {String? languageCode}) {
  final q = query.toLowerCase();
  return defaultCountries.where((country) {
    final nameToSearch = languageCode != null 
      ? country.getName(languageCode).toLowerCase()
      : country.name.toLowerCase();
    
    return country.code.toLowerCase().contains(q) ||
      nameToSearch.contains(q) ||
      country.dialCode.contains(q) ||
      country.iso3.toLowerCase().contains(q) ||
      (languageCode == null 
        ? country.translations.values.any((v) => v.toLowerCase().contains(q))
        : country.translations[languageCode]?.toLowerCase().contains(q) ?? false);
  }).toList();
}

  static List<Country> advancedSearch({
    String? code,
    String? currency,
    String? region,
    String? timezone,
    String? query,
  }) {
    var results = defaultCountries;
    
    if (code != null) results = results.where((c) => c.code == code).toList();
    if (currency != null) results = results.where((c) => c.currency == currency).toList();
    if (region != null) results = results.where((c) => c.region == region).toList();
    if (timezone != null) {
      results = results.where((c) => c.timezones.contains(timezone)).toList();
    }
    if (query != null) {
      final q = query.toLowerCase();
      results = results.where((c) =>
        c.code.toLowerCase().contains(q) ||
        c.name.toLowerCase().contains(q) ||
        c.translations.values.any((v) => v.toLowerCase().contains(q))
      ).toList();
    }
    
    return results;
  }
}